---==================================================================================================================---
---                                                                                                                  ---
---    Original Author(s) : NLTP_ASHES                                                                               ---
---    Edited : N/A                                                                                                  ---
---    Date : 29/08/2026                                                                                             ---
---    License : Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)           ---
---                                                                                                                  ---
---    DXML script used to modify some XML files according to some criteria.                                         ---
---                                                                                                                  ---
---==================================================================================================================---

-- ---------------------------------------------------------------------------------------------------------------------
-- DXML for ui_wheel_companion.xml
-- ---------------------------------------------------------------------------------------------------------------------

function dxml_ui_wheel_companion(xml_file_name, xml_obj)
    -- Only execute on gamedata\configs\ui\ui_wheel_companion.xml
    if xml_file_name ~= [[ui\ui_wheel_companion.xml]] and xml_file_name ~= [[ui\ui_wheel_companion_16.xml]] then
        return
    end

    -- Query the file to get the node(s) to modify
    local query = "wheel > background"
    local query_res = xml_obj:query(query)

    -- Expect one, and only one match
    assert(size_table(query_res) == 1, "Invalid number of results for '" .. query .. "', got '" .. size_table(query_res) .. "', expected '1'.")

    -- Get the resulting element
    local xml_elem = query_res[1]

    -- XML Code to inject
    local xml_inject = [[<window_name>wheel_background</window_name>]]

    -- Inject XML code
    xml_obj:insertFromXMLString(xml_inject, xml_elem, #xml_elem.kids)
end

-- ---------------------------------------------------------------------------------------------------------------------
-- Callbacks registration
-- ---------------------------------------------------------------------------------------------------------------------

function on_xml_read()
    RegisterScriptCallback("on_xml_read", dxml_ui_wheel_companion)
end