---==================================================================================================================---
---                                                                                                                  ---
---    Original Author(s) : NLTP_ASHES                                                                               ---
---    Edited : N/A                                                                                                  ---
---    Date : 04/06/2025                                                                                             ---
---    License : Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)           ---
---                                                                                                                  ---
---    Script used to handle the Nanosuit tactical map UI.                                                           ---
---                                                                                                                  ---
---==================================================================================================================---

-- ---------------------------------------------------------------------------------------------------------------------
-- Constants, global variables and imported functions
-- ---------------------------------------------------------------------------------------------------------------------

-- ---------------------------------------------------------------------------------------------------------------------
-- Tactical map UI class
-- ---------------------------------------------------------------------------------------------------------------------

class "ui_defibrillator" (CUIScriptWnd)

function ui_defibrillator:__init(core, parent) super()
    -- Variables
    self.m_core = core
    self.m_parent = parent

    -- Build UI
    self.m_xml = CScriptXmlInit()
    self.m_xml:ParseFile("ui_nanosuit_defibrillator.xml")

    self.m_ui_message = self.m_xml:InitTextWnd("message", self)
    arm.scale_ui(self.m_ui_message, true, true, "center")
end

function ui_defibrillator:__finalize()
end

function ui_defibrillator:destroy()
end

function ui_defibrillator:Update(force)
    CUIScriptWnd.Update(self)

    if not self.m_core.m_defibrillator.m_is_defibrillating then
        self.m_ui_message:Show(false)
        return
    else
        self.m_ui_message:Show(true)
    end

    self.m_ui_message:SetText("")

    if self.m_core.m_defibrillator:is_charging() then
        local time_remaining = self.m_core.m_defibrillator.m_charging_time_remaining
        time_remaining = time_remaining / 1000
        time_remaining = round(time_remaining)
        self.m_ui_message:SetText("DEFIBRILLATOR CHARGING... " .. tostring(time_remaining))
    end

    if self.m_core.m_defibrillator:is_ready() then
        self.m_ui_message:SetText("DEFIBRILLATOR READY [SPACE]")
    end

end
