---==================================================================================================================---
---                                                                                                                  ---
---    Original Author(s) : NLTP_ASHES                                                                               ---
---    Edited : N/A                                                                                                  ---
---    Date : 05/09/2026                                                                                             ---
---    License : Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)           ---
---                                                                                                                  ---
---    Script used to stylize the companion wheel UI like the rest of the Nanosuit HUD.                              ---
---                                                                                                                  ---
---==================================================================================================================---

-- ---------------------------------------------------------------------------------------------------------------------
-- Constants, global variables and imported functions
-- ---------------------------------------------------------------------------------------------------------------------

-- ---------------------------------------------------------------------------------------------------------------------
-- Companion wheel UI class
-- ---------------------------------------------------------------------------------------------------------------------

class "ui_companion_wheel" (CUIScriptWnd)

function ui_companion_wheel:__init(parent) super()
    -- Variables
    self.m_parent = parent
    self.m_allowed = nanosuit_mcm.get_config("general", "customize_companion_wheel")

    if not self.m_allowed then
        return
    end

    -- Initialize companion wheel if needed
    if not axr_companions.GUI then
        axr_companions.GUI = axr_companions.UIWheelCompanion()
    end

    -- Override wheel background
    axr_companions.GUI.background = axr_companions.GUI.dialog:FindChild("wheel_background"):cast_Static()
    axr_companions.GUI.background:InitTexture("ui_nanosuit_wheel_background")
    axr_companions.GUI.background:SetTextureColor(GetARGB(200, 255, 255, 255))

    -- Create wheel outline
    axr_companions.GUI.outline = axr_companions.GUI.xml:InitStatic("wheel:background", axr_companions.GUI.dialog)
    axr_companions.GUI.outline:InitTexture("ui_nanosuit_wheel_outline")

    -- Override info box background
    axr_companions.GUI.info_background = axr_companions.GUI.dialog_info:FindChild("info_background"):cast_Static()
    axr_companions.GUI.info_background:InitTexture("ui_nanosuit_wheel_info_background")
    axr_companions.GUI.info_background:SetTextureColor(GetARGB(200, 255, 255, 255))

    -- Create info box outline
    axr_companions.GUI.info_outline = axr_companions.GUI.xml:InitStatic("info:background", axr_companions.GUI.dialog_info)
    axr_companions.GUI.info_outline:InitTexture("ui_nanosuit_wheel_info_outline")
end

function ui_companion_wheel:destroy()
    if not self.m_allowed then
        return
    end

    -- Destroy wheel outline
    axr_companions.GUI.dialog:DetachChild(axr_companions.GUI.outline)
    axr_companions.GUI.outline = nil

    -- Destroy info outline
    axr_companions.GUI.dialog_info:DetachChild(axr_companions.GUI.info_outline)
    axr_companions.GUI.info_outline = nil

    -- Reset UI
    axr_companions.GUI:InitControls()
end

function ui_companion_wheel:Update(force)
    CUIScriptWnd.Update(self)

    if not self.m_allowed then
        return
    end

    if self.m_parent.m_core.m_malfunctor.m_allowed then
        axr_companions.GUI.outline:SetTextureColor(self.m_parent.m_colors.red)
        axr_companions.GUI.info_outline:SetTextureColor(self.m_parent.m_colors.red)
    else
        axr_companions.GUI.outline:SetTextureColor(self.m_parent.m_colors.background)
        axr_companions.GUI.info_outline:SetTextureColor(self.m_parent.m_colors.background)
    end
end
