---==================================================================================================================---
---                                                                                                                  ---
---    Original Author(s) : NLTP_ASHES                                                                               ---
---    Edited : N/A                                                                                                  ---
---    Date : 06/08/2026                                                                                             ---
---    License : Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)           ---
---                                                                                                                  ---
---    Script used to handle the malfunction logic of the Nanosuit addon.                                            ---
---                                                                                                                  ---
---==================================================================================================================---

-- ---------------------------------------------------------------------------------------------------------------------
-- Constants, global variables and imported functions
-- ---------------------------------------------------------------------------------------------------------------------

-- Imports
armor_modes_enum                    = nanosuit_utils.armor_modes_enum

-- Constants
pulse_anomaly_malfunction_dist_sqr  = 50 ^ 2
psi_storm_malfunction_dist_sqr      = 150 ^ 2
pulse_anomaly_off_time              = 20
psi_storm_off_time                  = 20
electric_shock_off_time             = 5

-- ---------------------------------------------------------------------------------------------------------------------
-- General functions
-- ---------------------------------------------------------------------------------------------------------------------

bind_anomaly_field_pulse_anomaly_hit = bind_anomaly_field.pulse_anomaly_hit
bind_anomaly_field.pulse_anomaly_hit = function(particle_pos)
    local ret = bind_anomaly_field_pulse_anomaly_hit(particle_pos)

    nextTick(function()
        local instance = nanosuit_core.get_instance()
        local is_in_range = distance_2d_sqr(db.actor:position(), particle_pos) <= pulse_anomaly_malfunction_dist_sqr
        if instance and is_in_range then
            instance.m_malfunctor:enable_malfunction(pulse_anomaly_off_time)
        end
        return true
    end)

    return ret
end

psi_storm_manager_CPsiStormManager_vortex_actor_hit = psi_storm_manager.CPsiStormManager.vortex_actor_hit
psi_storm_manager.CPsiStormManager.vortex_actor_hit = function(self, vortex)
    local ret = psi_storm_manager_CPsiStormManager_vortex_actor_hit(self, vortex)

    nextTick(function()
        local instance = nanosuit_core.get_instance()
        local is_in_range = distance_2d_sqr(db.actor:position(), vortex.particle_pos) <= psi_storm_malfunction_dist_sqr
        if instance and is_in_range then
            instance.m_malfunctor:enable_malfunction(psi_storm_off_time)
        end
        return true
    end)

    return ret
end

function actor_on_hit_callback(obj, amount, local_direction, who, bone_index)
    if not obj or obj:id() ~= AC_ID or not who or not nanosuit_utils.is_electro_anomaly(who) then
        return
    end
    nextTick(function()
        local instance = nanosuit_core.get_instance()
        if instance then
            instance.m_malfunctor:enable_malfunction(electric_shock_off_time)
        end
        return true
    end)
end

-- ---------------------------------------------------------------------------------------------------------------------
-- Callbacks registration
-- ---------------------------------------------------------------------------------------------------------------------

function on_game_start()
    RegisterScriptCallback("actor_on_hit_callback", actor_on_hit_callback)
end

-- ---------------------------------------------------------------------------------------------------------------------
-- Malfunction class
-- ---------------------------------------------------------------------------------------------------------------------

class "malfunctor"

function malfunctor:__init(core)
    self.m_core = core

    -- Variables
    self.m_enabled = false
    self.m_duration = nil
end

function malfunctor:destroy()
    self.m_core = nil
end

function malfunctor:save()
    return {
        enabled = self.m_enabled,
        duration = self.m_duration
    }
end

function malfunctor:load(m_data)
    if m_data.enabled then
        self:enable_malfunction(m_data.duration)
    end
end

function malfunctor:enable_malfunction(duration)
    self.m_duration = duration

    if not self.m_enabled then
        self.m_enabled = true

        self.m_core:change_mode(armor_modes_enum.armor, false)
        self.m_core.m_energy:use_energy(100)

        if self.m_core.m_energy_off_voiced and not self.m_core.m_sounds.energy_off:playing() then
            self.m_core.m_sounds.energy_off:play_at_pos(db.actor, VEC_ZERO, 0, sound_object.s2d)
        end

        if self.m_duration ~= nil then
            CreateTimeEvent("nanosuit_malfunction", "disable", self.m_duration, function()
                self:disable_malfunction()
                return true
            end)
        end
    elseif self.m_duration ~= nil then
        ResetTimeEvent("nanosuit_malfunction", "disable", duration)
    end
end

function malfunctor:disable_malfunction()
    if self.m_enabled then
        self.m_enabled = false
        self.m_core:change_mode(self.m_core.m_default_mode, true)
        self.m_core.m_energy.m_last_use = time_global()
    end
end
