---==================================================================================================================---
---                                                                                                                  ---
---    Original Author(s) : NLTP_ASHES                                                                               ---
---    Edited : N/A                                                                                                  ---
---    Date : 05/09/2026                                                                                             ---
---    License : Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)           ---
---                                                                                                                  ---
---    Script used to stylize the ammo wheel UI like the rest of the Nanosuit HUD.                                   ---
---                                                                                                                  ---
---==================================================================================================================---

-- ---------------------------------------------------------------------------------------------------------------------
-- Constants, global variables and imported functions
-- ---------------------------------------------------------------------------------------------------------------------

-- ---------------------------------------------------------------------------------------------------------------------
-- Ammo wheel UI class
-- ---------------------------------------------------------------------------------------------------------------------

class "ui_ammo_wheel" (CUIScriptWnd)

function ui_ammo_wheel:__init(parent) super()
    -- Variables
    self.m_parent = parent
    self.m_allowed = nanosuit_mcm.get_config("general", "customize_ammo_wheel")

    if not self.m_allowed then
        return
    end

    -- Initialize ammo wheel if needed
    if not item_weapon.GUI then
        item_weapon.GUI = item_weapon.UIWheelAmmo()
    end

    -- Create outline
    item_weapon.GUI.outline = item_weapon.GUI.xml:InitStatic("wheel:background", item_weapon.GUI.dialog)
    item_weapon.GUI.outline:InitTexture("ui_nanosuit_wheel_outline")

    -- Override background
    item_weapon.GUI.background:InitTexture("ui_nanosuit_wheel_background")
    item_weapon.GUI.background:SetTextureColor(GetARGB(200, 255, 255, 255))
end

function ui_ammo_wheel:destroy()
    if not self.m_allowed then
        return
    end

    -- Destroy outline
    item_weapon.GUI.dialog:DetachChild(item_weapon.GUI.outline)
    item_weapon.GUI.outline = nil

    -- Reset UI
    item_weapon.GUI:InitControls()
end

function ui_ammo_wheel:Update(force)
    CUIScriptWnd.Update(self)

    if not self.m_allowed then
        return
    end

    if self.m_parent.m_core.m_malfunctor.m_allowed then
        item_weapon.GUI.outline:SetTextureColor(self.m_parent.m_colors.red)
    else
        item_weapon.GUI.outline:SetTextureColor(self.m_parent.m_colors.background)
    end
end
