---==================================================================================================================---
---                                                                                                                  ---
---    Original Author(s) : NLTP_ASHES                                                                               ---
---    Edited : N/A                                                                                                  ---
---    Date : 03/09/2026                                                                                             ---
---    License : Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)           ---
---                                                                                                                  ---
---    Script used to handle the Nanosuit's built-in nanovision system.                                              ---
---                                                                                                                  ---
---==================================================================================================================---

-- ---------------------------------------------------------------------------------------------------------------------
-- Constants, global variables and imported functions
-- ---------------------------------------------------------------------------------------------------------------------

-- Imports
actor_slots_enum          = nanosuit_utils.actor_slots_enum
energy_drain_enum         = nanosuit_utils.energy_drain_enum

-- ---------------------------------------------------------------------------------------------------------------------
-- Defibrillator class
-- ---------------------------------------------------------------------------------------------------------------------

class "nanovision"

function nanovision:__init(core)
    self.m_core = core
    self.m_energy_drain = 1
    self.m_energy_drain_rate = 500
    self.m_energy_use_on_activate = 5
    self.m_sounds = {
        on = sound_object([[nanosuit\nanovision\nanovision_on]]),
        off = sound_object([[nanosuit\nanovision\nanovision_off]]),
        loop = sound_object([[nanosuit\nanovision\nanovision_loop]])
    }

    RegisterScriptCallback("on_key_press", self)
    RegisterScriptCallback("actor_on_update", self)
end

function nanovision:destroy()
    if self:is_active() then
        self:deactivate()
    end

    self.m_core = nil

    UnregisterScriptCallback("on_key_press", self)
    UnregisterScriptCallback("actor_on_update", self)
end

function nanovision:activate()
    -- Consume energy on activation
    self.m_core.m_energy:use_energy(self.m_energy_use_on_activate)

    -- Consume energy while activated
    self.m_core.m_energy:add_drain(energy_drain_enum.nanovision, self.m_energy_drain_rate, self.m_energy_drain)

    -- Play sounds
    self.m_sounds.on:play_at_pos(db.actor, VEC_ZERO, 0, sound_object.s2d)
    self.m_sounds.loop:play_at_pos(db.actor, VEC_ZERO, 0, sound_object.s2d + sound_object.looped)

    -- Turn shader on
    local n_tubes = tostring(20) -- Num Tubes (1,2,4,1.1,1.2) outputs x.10, x.20, x.40, x.11, or x.12
    local vignette = tostring(math.floor(0)) -- Vignette Amount (0.0 to 1.0) outputs 0.z to 100.z in 1. increment
    local flip_down = tostring(math.floor(100)) -- Flip down amount - outputs 1.x to 100.x
    local radius = tostring(math.floor(9)) -- Radius for NVG effect - outputs 0.0 to 0.9

    get_console():execute("r__heatvision 1")
    get_console():execute("heat_vision_args_1 (0." .. n_tubes .. ",0.0," .. vignette .. ".0,0.0)")
    get_console():execute("heat_vision_args_2 (" .. flip_down .. ".0,0." .. radius .. ",0.0,0.0)")
end

function nanovision:deactivate()
    self.m_core.m_energy:remove_drain(energy_drain_enum.nanovision)

    -- Play sounds
    self.m_sounds.off:play_at_pos(db.actor, VEC_ZERO, 0, sound_object.s2d)
    self.m_sounds.loop:stop()

    -- Turn shader off
    get_console():execute("r__heatvision 0")
    get_console():execute("heat_vision_args_1 (0.0,0.0,0.0,0.0)")
    get_console():execute("heat_vision_args_2 (0.0,0.0,0.0,0.0)")
end

function nanovision:can_activate()
    local is_enabled = nanosuit_mcm.get_config("general", "use_nanovision")
    local has_torch = db.actor:item_in_slot(actor_slots_enum.torch) ~= nil
    local has_energy = self.m_core.m_energy.m_level > 0
    local nightvision_on = self.m_core.m_nightvision:is_active()
    return is_enabled and not has_torch and has_energy and not nightvision_on
end

function nanovision:is_active()
    return get_console():get_bool("r__heatvision")
end

function nanovision:on_key_press(dik)
    if dik == nanosuit_mcm.get_config("keybindings", "nanovision") then
        if self:is_active() then
            self:deactivate()
        elseif self:can_activate() then
            self:activate()
        end
    end
end

function nanovision:actor_on_update()
    if not self:is_active() then
        return
    end

    if not self:can_activate() then
        self:deactivate()
        return
    end
end
