---==================================================================================================================---
---                                                                                                                  ---
---    Original Author(s) : NLTP_ASHES                                                                               ---
---    Edited : N/A                                                                                                  ---
---    Date : 05/09/2026                                                                                             ---
---    License : Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)           ---
---                                                                                                                  ---
---    Script used to stylize the companion list UI like the rest of the Nanosuit HUD.                              ---
---                                                                                                                  ---
---==================================================================================================================---

-- ---------------------------------------------------------------------------------------------------------------------
-- Constants, global variables and imported functions
-- ---------------------------------------------------------------------------------------------------------------------

-- ---------------------------------------------------------------------------------------------------------------------
-- Companion list UI class
-- ---------------------------------------------------------------------------------------------------------------------

class "ui_companion_list" (CUIScriptWnd)

function ui_companion_list:__init(parent) super()
    -- Variables
    self.m_parent = parent
    self.m_allowed = nanosuit_mcm.get_config("general", "customize_companion_list")

    if not self.m_allowed then
        return
    end

    -- Initialize companion list if needed
    if not axr_companions.HUD then
        axr_companions.HUD = axr_companions.UICompanionList()
        get_hud():AddDialogToRender(axr_companions.HUD)
    end

    local xml = utils_xml.get_hud_xml()

    for idx, info in pairs(axr_companions.HUD.companion_info) do
        -- Override background
        info.background:InitTexture("ui_nanosuit_companion_list_background")
        info.background:SetTextureColor(GetARGB(200, 255, 255, 255))

        -- Create outline
        info.outline = xml:InitStatic("companion_list:slot:background", info.base)
        info.outline:InitTexture("ui_nanosuit_companion_list_outline")
        utils_xml.correct_ratio(info.outline)
    end
end

function ui_companion_list:destroy()
    if not self.m_allowed then
        return
    end

    -- If we are being called from actor_on_net_destroy, companion list could have been destroyed before us
    if not axr_companions.HUD then
        return
    end

    -- Destroy outlines
    for idx, info in pairs(axr_companions.HUD.companion_info) do
        info.base:DetachChild(info.outline)
        info.outline = nil
    end

    -- Reset UI
    axr_companions.HUD:InitControls()
end

function ui_companion_list:Update(force)
    CUIScriptWnd.Update(self)

    if not self.m_allowed then
        return
    end

    for idx, info in pairs(axr_companions.HUD.companion_info) do
        if self.m_parent.m_core.m_malfunctor.m_allowed then
            info.outline:SetTextureColor(self.m_parent.m_colors.red)
        else
            info.outline:SetTextureColor(self.m_parent.m_colors.background)
        end
    end
end
