---==================================================================================================================---
---                                                                                                                  ---
---    Original Author(s) : NLTP_ASHES                                                                               ---
---    Edited : N/A                                                                                                  ---
---    Date : 08/02/2026                                                                                             ---
---    License : Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)           ---
---                                                                                                                  ---
---    Script used to handle the logic of armor mode of the Nanosuit addon.                                          ---
---                                                                                                                  ---
---==================================================================================================================---

-- ---------------------------------------------------------------------------------------------------------------------
-- Constants, global variables and imported functions
-- ---------------------------------------------------------------------------------------------------------------------

-- Imports
hit_types_enum          = nanosuit_utils.hit_types_enum

-- ---------------------------------------------------------------------------------------------------------------------
-- Armor mode class
-- ---------------------------------------------------------------------------------------------------------------------

class "armor" (nanosuit_mode.abstract_mode)

function armor:__init(core, name) super(core, name)
    -- Sound effects
    self.m_sounds.armor_on = sound_object([[nanosuit\modes\armor\mode_armor_on]])
    self.m_sounds.impacts = {
        sound_object([[nanosuit\modes\armor\mode_armor_hit_01]]),
        sound_object([[nanosuit\modes\armor\mode_armor_hit_02]]),
        sound_object([[nanosuit\modes\armor\mode_armor_hit_03]]),
        sound_object([[nanosuit\modes\armor\mode_armor_hit_04]]),
        sound_object([[nanosuit\modes\armor\mode_armor_hit_05]])
    }
end

function armor:apply(play_voice)
    nanosuit_mode.abstract_mode.apply(self, play_voice, "blue")

    -- Play sounds
    self.m_sounds.armor_on:play_at_pos(db.actor, VEC_ZERO, 0, sound_object.s2d)
end

function armor:remove(is_destroying)
    nanosuit_mode.abstract_mode.remove(self, is_destroying)
end

function armor:on_before_hit_after_calcs(scripted_hit, target, bone_id)
    nanosuit_mode.abstract_mode.on_before_hit_after_calcs(self, scripted_hit, target, bone_id)

    -- Only apply to actor
    if target:id() ~= AC_ID then
        return
    end

    -- Play sound
    if self.m_core.m_energy.m_level > 0 then
        if scripted_hit.type == hit_types_enum.fire_wound then
            local sfx = self.m_sounds.impacts[math.random(1, #self.m_sounds.impacts)]
            sfx:play_at_pos(db.actor, VEC_ZERO, 0, sound_object.s2d)
        end
    end
end