---==================================================================================================================---
---                                                                                                                  ---
---    Original Author(s) : NLTP_ASHES                                                                               ---
---    Edited : N/A                                                                                                  ---
---    Date : 08/08/2026                                                                                             ---
---    License : Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)           ---
---                                                                                                                  ---
---    Script used to handle all the necessary intercepts to make the Nanosuit addon compatible with other addons.   ---
---                                                                                                                  ---
---==================================================================================================================---

-- ---------------------------------------------------------------------------------------------------------------------
-- Constants, global variables and imported functions
-- ---------------------------------------------------------------------------------------------------------------------

-- Imports
actor_slots_enum        = nanosuit_utils.actor_slots_enum

-- ---------------------------------------------------------------------------------------------------------------------
-- First Person Visible Body v6.0
-- ---------------------------------------------------------------------------------------------------------------------

if se_legs then

    function is_legs(obj)
        -- FIXME: A better check is needed
        if obj and obj:section() == "outfit_nanosuit_legs" then
            return true
        end
        return false
    end

    nanosuit_mode_cloak_cloak___init = nanosuit_mode_cloak.cloak.__init
    nanosuit_mode_cloak.cloak.__init = function(self, core, name)
        local res = nanosuit_mode_cloak_cloak___init(self, core, name)

        self.m_cache.legs_shaders = { world = nil }

        return res
    end

    nanosuit_mode_cloak_cloak_apply = nanosuit_mode_cloak.cloak.apply
    nanosuit_mode_cloak.cloak.apply = function(self, play_voice)
        local res = nanosuit_mode_cloak_cloak_apply(self, play_voice)

        RegisterScriptCallback("game_object_on_net_spawn", self)
        RegisterScriptCallback("game_object_on_net_destroy", self)

        local legs_id = se_legs.LegsTbl[level.name()]
        local legs_obj = legs_id and level.object_by_id(legs_id)
        if legs_obj then
            self:set_legs_invisible(legs_obj)
        end

        return res
    end

    nanosuit_mode_cloak_cloak_remove = nanosuit_mode_cloak.cloak.remove
    nanosuit_mode_cloak.cloak.remove = function(self, is_destroying)
        local res = nanosuit_mode_cloak_cloak_remove(self, is_destroying)

        UnregisterScriptCallback("game_object_on_net_spawn", self)
        UnregisterScriptCallback("game_object_on_net_destroy", self)

        local legs_id = se_legs.LegsTbl[level.name()]
        local legs_obj = legs_id and level.object_by_id(legs_id)
        if legs_obj then
            self:set_legs_visible(legs_obj)
        end

        return res
    end

    nanosuit_mode_cloak.cloak.set_legs_visible = function(self, legs_obj)
        for idx, save in pairs(self.m_cache.legs_shaders.world) do
            legs_obj:set_shader(idx, save.shader, save.texture)
        end
        self.m_cache.legs_shaders = { world = nil }
    end

    nanosuit_mode_cloak.cloak.set_legs_invisible = function(self, legs_obj)
        self.m_cache.legs_shaders = { world = legs_obj:get_shaders() }
        for idx, _ in pairs(self.m_cache.legs_shaders.world) do
            legs_obj:set_shader(idx, self.m_cloak_shader, self.m_cloak_texture)
        end
    end

    nanosuit_mode_cloak.cloak.game_object_on_net_spawn = function(self, obj)
        if is_legs(obj) then
            CreateTimeEvent("nanosuit_legs_spawn", obj:name(), 0, function(id)
                local obj_now = level.object_by_id(id)
                if obj_now then
                    self:set_legs_invisible(obj_now)
                end
                return true
            end, obj:id())
        end
    end

    nanosuit_mode_cloak.cloak.game_object_on_net_destroy = function(self, obj)
        if is_legs(obj) then
        self:set_legs_visible(obj)
        end
    end
end

-- ---------------------------------------------------------------------------------------------------------------------
-- Hunger, thirst, sleepiness bars v1.01
-- ---------------------------------------------------------------------------------------------------------------------

nanosuit_ui_indicators_ui_indicators___init_htsb = nanosuit_ui_indicators.ui_indicators.__init
nanosuit_ui_indicators.ui_indicators.__init = function(self, parent)
    local res = nanosuit_ui_indicators_ui_indicators___init_htsb(self, parent)

    self.m_config_override["Thirst"] = { icon = "ui_nanosuit_ind_indicator_thirst", background = "ui_nanosuit_ind_indicator_slot" }
    self.m_config_override["Sleep"] = { icon = "ui_nanosuit_ind_indicator_sleep", background = "ui_nanosuit_ind_indicator_slot" }

    return res
end

-- ---------------------------------------------------------------------------------------------------------------------
-- Campfire Healing And Designated Savepoint indicator v2.1
-- ---------------------------------------------------------------------------------------------------------------------

if actor_status_campfire then
    nanosuit_ui_indicators_ui_indicators___init_chdsi = nanosuit_ui_indicators.ui_indicators.__init
    nanosuit_ui_indicators.ui_indicators.__init = function(self, parent)
        local res = nanosuit_ui_indicators_ui_indicators___init_chdsi(self, parent)

        self.m_config_override["CampfireIcon"] = { icon = "ui_nanosuit_ind_booster_cf", background = "ui_nanosuit_ind_booster_slot" }

        self.m_campfire_overrides = {
            ["ui_indicator_zone_campfire"] = "ui_nanosuit_ind_booster_cf",
            ["ui_indicator_zone_campfire_heal"] = "ui_nanosuit_ind_booster_cf_heal",
            ["ui_indicator_zone_campfire_save"] = "ui_nanosuit_ind_booster_cf_save",
            ["ui_indicator_zone_campfire_healsave"] = "ui_nanosuit_ind_booster_cf_healsave",
            ["ui_indicator_zone_campfire_alt_color"] = "ui_nanosuit_ind_booster_cf",
            ["ui_indicator_zone_campfire_heal_alt_color"] = "ui_nanosuit_ind_booster_cf_heal",
            ["ui_indicator_zone_campfire_save_alt_color"] = "ui_nanosuit_ind_booster_cf_save",
            ["ui_indicator_zone_campfire_healsave_alt_color"] = "ui_nanosuit_ind_booster_cf_healsave",
            ["ui_indicator_zone_campfire_alt_bw"] = "ui_nanosuit_ind_booster_cf",
            ["ui_indicator_zone_campfire_heal_alt_bw"] = "ui_nanosuit_ind_booster_cf_heal",
            ["ui_indicator_zone_campfire_save_alt_bw"] = "ui_nanosuit_ind_booster_cf_save",
            ["ui_indicator_zone_campfire_healsave_alt_bw"] = "ui_nanosuit_ind_booster_cf_healsave"
        }

        return res
    end

    nanosuit_ui_indicators_ui_indicators_get_config_override_chdsi = nanosuit_ui_indicators.ui_indicators.get_config_override
    nanosuit_ui_indicators.ui_indicators.get_config_override = function(self, name, key)
        local res = nanosuit_ui_indicators_ui_indicators_get_config_override_chdsi(self, name, key)

        if name == "CampfireIcon" and key == "icon" then
            local indicator = actor_status.indicators["CampfireIcon"]
            local override = indicator and self.m_campfire_overrides[indicator.icon]
            return override or "ui_nanosuit_ind_booster_cf"
        end

        return res
    end
end

-- ---------------------------------------------------------------------------------------------------------------------
-- Body Health System Redux v2.0.2
-- ---------------------------------------------------------------------------------------------------------------------

if zzz_player_injuries then
    nanosuit_ui_hud_ui_hud_Update_bhs = nanosuit_ui_hud.ui_hud.Update
    nanosuit_ui_hud.ui_hud.Update = function(self, force)
        nanosuit_ui_hud_ui_hud_Update_bhs(self, force)
        zzz_player_injuries.show_hud_type = 0
    end
end

-- ---------------------------------------------------------------------------------------------------------------------
-- Heat Vision v1.3
-- ---------------------------------------------------------------------------------------------------------------------

if z_heatvision then
    nanosuit_core_core___init = nanosuit_core.core.__init
    nanosuit_core.core.__init = function(self, name)
        local res = nanosuit_core_core___init(self, name)

        self.m_nanovision = nanosuit_nanovision.nanovision(self)

        return res
    end

    nanosuit_core_core_destroy = nanosuit_core.core.destroy
    nanosuit_core.core.destroy = function(self)
        local res = nanosuit_core_core_destroy(self)

        self.m_nanovision:destroy()

        return res
    end

    nanosuit_nightvision_nightvision_can_activate = nanosuit_nightvision.nightvision.can_activate
    nanosuit_nightvision.nightvision.can_activate = function(self)
        local res = nanosuit_nightvision_nightvision_can_activate(self)

        return res and not self.m_core.m_nanovision:is_active()
    end
end

-- ---------------------------------------------------------------------------------------------------------------------
-- Faction Identification UI v1.2.2
-- ---------------------------------------------------------------------------------------------------------------------

if factionid_hud_mcm then
    nanosuit_ui_hud_ui_hud_get_elements_to_move_factionid = nanosuit_ui_hud.ui_hud.get_elements_to_move
    nanosuit_ui_hud.ui_hud.get_elements_to_move = function(self)
        local elements_to_move = nanosuit_ui_hud_ui_hud_get_elements_to_move_factionid(self)
        if factionid_hud_mcm.HUD then
            table.insert(elements_to_move, { element = factionid_hud_mcm.HUD, x = 115, y = -20 })
        end
        return elements_to_move
    end
end