---==================================================================================================================---
---                                                                                                                  ---
---    Original Author(s) : NLTP_ASHES                                                                               ---
---    Edited : N/A                                                                                                  ---
---    Date : 03/09/2026                                                                                             ---
---    License : Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)           ---
---                                                                                                                  ---
---    Script used to execute debug functions to help in development.                                                ---
---                                                                                                                  ---
---==================================================================================================================---

-- ---------------------------------------------------------------------------------------------------------------------
-- Constants, global variables and imported functions
-- ---------------------------------------------------------------------------------------------------------------------

-- Variables
holding_ctrl            = false
x_transforms            = 0
y_transforms            = 0
poly_point              = 0
seq                     = nil
clr_idx, clr            = 1, { [1] = 125, [2] = 125, [3] = 102 }

-- ---------------------------------------------------------------------------------------------------------------------
-- General functions
-- ---------------------------------------------------------------------------------------------------------------------

function on_key_press_tacmap(dik)
    if dik == DIK_keys.DIK_LCONTROL then
        holding_ctrl = true
    end
    if not nanosuit_core.get_instance() then
        return
    end

    local pos = nil
    if poly_point == 0 then
        pos = nanosuit_core.get_instance().m_hud.m_ui_tacmap.m_player
    else
        pos = nanosuit_core.get_instance().m_hud.m_ui_tacmap.m_tacmap_bounds[poly_point]
    end

    local transform = holding_ctrl and 10 or 1
    if dik == DIK_keys.DIK_DOWN then
        pos.y = pos.y + transform
    elseif dik == DIK_keys.DIK_UP then
        pos.y = pos.y - transform
    elseif dik == DIK_keys.DIK_LEFT then
        pos.x = pos.x - transform
    elseif dik == DIK_keys.DIK_RIGHT then
        pos.x = pos.x + transform
    elseif dik == DIK_keys.DIK_ADD then
        if poly_point < 7 then
            poly_point = poly_point + 1
            printf("[NS] Poly point set to : poly_point:%s", poly_point)
        end
    elseif dik == DIK_keys.DIK_SUBTRACT then
        if poly_point > 1 then
            poly_point = poly_point - 1
            printf("[NS] Poly point set to : poly_point:%s", poly_point)
        else
            poly_point = 0
            printf("[NS] Poly point set to player")
        end
    elseif dik == DIK_keys.DIK_HOME then
        printf("[NS] Poly : x:%s y:%s", pos.x, pos.y)
        return
    end
end

function on_key_press_status(dik)
    if dik == DIK_keys.DIK_LCONTROL then
        holding_ctrl = true
    end
    if not nanosuit_core.get_instance() then
        return
    end

    local static = actor_status.HUD.dialog

    local pos = vector2():set(static:GetWndPos().x, static:GetWndPos().y)

    local transform = holding_ctrl and 10 or 1
    if dik == DIK_keys.DIK_DOWN then
        pos.y = pos.y + transform
        y_transforms = y_transforms + transform
    elseif dik == DIK_keys.DIK_UP then
        pos.y = pos.y - transform
        y_transforms = y_transforms - transform
    elseif dik == DIK_keys.DIK_LEFT then
        pos.x = pos.x - transform
        x_transforms = x_transforms - transform
    elseif dik == DIK_keys.DIK_RIGHT then
        pos.x = pos.x + transform
        x_transforms = x_transforms + transform
    elseif dik == DIK_keys.DIK_HOME then
        printf("[NS] Static transforms: x:%s y:%s", x_transforms, y_transforms)
    end
    static:SetWndPos(pos)
end

function on_key_press_vap(dik)
    if dik == DIK_keys.DIK_J then
        nanosuit_core.get_instance().m_vaporizer:vaporize(db.actor, true)
    end

    local obj = level.get_target_obj()
    if not obj then
        return
    end

    if dik == DIK_keys.DIK_L then
        obj:set_visual_name([[nanosuit\nanosuit\nanosuit_tp]])
    elseif dik == DIK_keys.DIK_K then
        nanosuit_core.get_instance().m_vaporizer:vaporize(obj, false)
    end
end

function on_key_press_malfunction(dik)
    if dik == DIK_keys.DIK_K then
        nanosuit_core.get_instance().m_malfunctor:enable_malfunction(nil)
        elseif dik == DIK_keys.DIK_L then
        nanosuit_core.get_instance().m_malfunctor:disable_malfunction()
    end
end

function on_key_press_defib(dik)
    if dik == DIK_keys.DIK_K then
        if not nanosuit_core.get_instance().m_defibrillator.m_enabled then
            nanosuit_core.get_instance().m_defibrillator:defibrillate()
        else
            level.remove_cam_effector(nanosuit_defibrillator.cam_effector_start_id)
            nanosuit_utils.remove_pp_effector(nanosuit_defibrillator.pp_effector_b_id)
            nanosuit_utils.remove_pp_effector(nanosuit_defibrillator.pp_effector_ftb_id)
        end
    end
end

function on_key_press_defib_ui(dik)
    if dik == DIK_keys.DIK_K then
        nanosuit_core.get_instance().m_defibrillator.m_enabled = true
        nanosuit_core.get_instance().m_defibrillator.m_charging = not nanosuit_core.get_instance().m_defibrillator.m_charging
        nanosuit_core.get_instance().m_defibrillator.m_charging_time_remaining = 3000
        nanosuit_core.get_instance().m_defibrillator.m_charging_time_last_update = time_global()
    end
end

function on_key_press_chainable(dik)
    if dik == DIK_keys.DIK_K then
        if not seq then
            seq = dummy_sequence(nanosuit_core.get_instance())
            seq:from(seq.action_1)
            seq:after(seq.action_2, 5)
            seq:after(seq.action_3, 0)
            seq:after(seq.action_4, 5)
            seq:execute()
        else
            seq:destroy()
            seq = nil
        end
    end
end

function on_key_press_color(dik)
    if dik == DIK_keys.DIK_LCONTROL then
        holding_ctrl = true
    end

    if dik == DIK_keys.DIK_DOWN then
        clr[clr_idx] = clr[clr_idx] - (holding_ctrl and 5 or 1)
    elseif dik == DIK_keys.DIK_UP then
        clr[clr_idx] = clr[clr_idx] + (holding_ctrl and 5 or 1)
    elseif dik == DIK_keys.DIK_LEFT then
        clr_idx = clr_idx - 1
        if clr_idx < 1 then
            clr_idx = 3
        end
    elseif dik == DIK_keys.DIK_RIGHT then
        clr_idx = clr_idx + 1
        if clr_idx > 3 then
            clr_idx = 1
        end
    elseif dik == DIK_keys.DIK_HOME then
        printf("[NS] Color : %s,%s,%s", clr[1], clr[2], clr[3])
    end

    nanosuit_core.get_instance().m_hud.m_colors.background = GetARGB(200, nanosuit_debug.clr[1], nanosuit_debug.clr[2], nanosuit_debug.clr[3])
end

function on_key_release(dik)
    if dik == DIK_keys.DIK_LCONTROL then
        holding_ctrl = false
    end
end

function actor_on_update_tacmap_border()
    local instance = nanosuit_core.get_instance()
    if not instance then
        return
    end

    local pos1 = game.ui2world(instance.m_hud.m_ui_tacmap.m_ui_map.m_tacmap_bounds[1])
    local pos2 = game.ui2world(instance.m_hud.m_ui_tacmap.m_ui_map.m_tacmap_bounds[2])
    local pos3 = game.ui2world(instance.m_hud.m_ui_tacmap.m_ui_map.m_tacmap_bounds[3])
    local pos4 = game.ui2world(instance.m_hud.m_ui_tacmap.m_ui_map.m_tacmap_bounds[4])
    local pos5 = game.ui2world(instance.m_hud.m_ui_tacmap.m_ui_map.m_tacmap_bounds[5])
    local pos6 = game.ui2world(instance.m_hud.m_ui_tacmap.m_ui_map.m_tacmap_bounds[6])
    local pos7 = game.ui2world(instance.m_hud.m_ui_tacmap.m_ui_map.m_tacmap_bounds[7])

    if not line1 then
        line1 = debug_render.add_object(99001, DBG_ScriptObject.line):cast_dbg_line()
        line1.color = fcolor():set(1,0,0,1)
        line1.visible = true
    end
    line1.point_a = pos1
    line1.point_b = pos2

    if not line2 then
        line2 = debug_render.add_object(99002, DBG_ScriptObject.line):cast_dbg_line()
        line2.color = fcolor():set(1,0,0,1)
        line2.visible = true
    end
    line2.point_a = pos2
    line2.point_b = pos3

    if not line3 then
        line3 = debug_render.add_object(99003, DBG_ScriptObject.line):cast_dbg_line()
        line3.color = fcolor():set(1,0,0,1)
        line3.visible = true
    end
    line3.point_a = pos3
    line3.point_b = pos4

    if not line4 then
        line4 = debug_render.add_object(99004, DBG_ScriptObject.line):cast_dbg_line()
        line4.color = fcolor():set(1,0,0,1)
        line4.visible = true
    end
    line4.point_a = pos4
    line4.point_b = pos5

    if not line5 then
        line5 = debug_render.add_object(99005, DBG_ScriptObject.line):cast_dbg_line()
        line5.color = fcolor():set(1,0,0,1)
        line5.visible = true
    end
    line5.point_a = pos5
    line5.point_b = pos6

    if not line6 then
        line6 = debug_render.add_object(99006, DBG_ScriptObject.line):cast_dbg_line()
        line6.color = fcolor():set(1,0,0,1)
        line6.visible = true
    end
    line6.point_a = pos6
    line6.point_b = pos7

    if not line7 then
        line7 = debug_render.add_object(99007, DBG_ScriptObject.line):cast_dbg_line()
        line7.color = fcolor():set(1,0,0,1)
        line7.visible = true
    end
    line7.point_a = pos7
    line7.point_b = pos1
end

-- ---------------------------------------------------------------------------------------------------------------------
-- Callbacks registration
-- ---------------------------------------------------------------------------------------------------------------------

function on_game_start()
    --RegisterScriptCallback("on_key_press", on_key_press_tacmap)
    --RegisterScriptCallback("on_key_press", on_key_press_status)
    --RegisterScriptCallback("on_key_press", on_key_press_vap)
    --RegisterScriptCallback("on_key_press", on_key_press_malfunction)
    --RegisterScriptCallback("on_key_press", on_key_press_defib)
    --RegisterScriptCallback("on_key_press", on_key_press_defib_ui)
    --RegisterScriptCallback("on_key_press", on_key_press_chainable)
    --RegisterScriptCallback("on_key_press", on_key_press_color)
    --RegisterScriptCallback("on_key_release", on_key_release)
    --RegisterScriptCallback("actor_on_update", actor_on_update_tacmap_border)
end

-- ---------------------------------------------------------------------------------------------------------------------
-- Dummy anim seq
-- ---------------------------------------------------------------------------------------------------------------------

class "dummy_sequence" (nanosuit_sequence.scripted_sequence)

function dummy_sequence:__init() super()
end

function dummy_sequence:destroy()
    nanosuit_sequence.scripted_sequence.destroy(self)
end

function dummy_sequence:action_1()
    printf("[NS] Dummy anim seq action 1 called")
    return true
end

function dummy_sequence:action_2()
    printf("[NS] Dummy anim seq action 2 called")
    return true
end

function dummy_sequence:action_3()
    printf("[NS] Dummy anim seq action 3 called")
    return true
end

function dummy_sequence:action_4()
    printf("[NS] Dummy anim seq action 4 called")
    return true
end