---==================================================================================================================---
---                                                                                                                  ---
---    Original Author(s) : NLTP_ASHES                                                                               ---
---    Edited : N/A                                                                                                  ---
---    Date : 12/09/2026                                                                                             ---
---    License : Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)           ---
---                                                                                                                  ---
---    Script used to handle the mysterious interferences with the Nanosuit...                                       ---
---                                                                                                                  ---
---==================================================================================================================---

-- ---------------------------------------------------------------------------------------------------------------------
-- Constants, global variables and imported functions
-- ---------------------------------------------------------------------------------------------------------------------

-- ---------------------------------------------------------------------------------------------------------------------
-- Interference class
-- ---------------------------------------------------------------------------------------------------------------------

class "interference"

function interference:__init(core)
    -- Variables
    self.m_active = false
    self.m_range_sqr = 10 ^ 2
    self.m_effector = { id = 3592, path = [[nanosuit\post_process\interference.ppe]] }
    self.m_sound = sound_object([[nanosuit\misc\interference]])
    self.m_locations = {
        self:get_location_if_same_level("nanosuit_interference_sarcophagus"),
        self:get_location_if_same_level("nanosuit_interference_truck_cemetery"),
        self:get_location_if_same_level("nanosuit_interference_jupiter")
    }

    -- Callbacks
    RegisterScriptCallback("actor_on_update", self)
end

function interference:destroy()
    if self.m_active then
        self:deactivate()
    end

    -- Callbacks
    UnregisterScriptCallback("actor_on_update", self)
end

function interference:actor_on_update()
    local distance_sqr = self:get_distance_sqr()

    if distance_sqr and not self.m_active then
        self:activate()
    elseif not distance_sqr and self.m_active then
        self:deactivate()
    end

    if self.m_active then
        self:update_strength(distance_sqr)
    end
end

function interference:activate()
    self.m_active = true
    level.add_pp_effector(self.m_effector.path, self.m_effector.id, true)
end

function interference:deactivate()
    self.m_active = false
    self.m_sound:stop()
    level.remove_pp_effector(self.m_effector.id)
end

function interference:update_strength(distance_sqr)
    local strength = self:get_strength(distance_sqr)

    level.set_pp_effector_factor(self.m_effector.id, strength)

    if not self.m_sound:playing() then
        self.m_sound:play_at_pos(db.actor, VEC_ZERO, 0, sound_object.s2d + sound_object.looped)
    end
    self.m_sound.volume = strength
end

function interference:get_distance_sqr()
    local closest
    for idx, location in pairs(self.m_locations) do
        local distance_sqr = db.actor:position():distance_to_sqr(location.position)
        if distance_sqr <= self.m_range_sqr and (not closest or distance_sqr < closest) then
            closest = distance_sqr
        end
    end
    return closest
end

function interference:get_strength(distance_sqr)
    return 1 - math.sqrt(clamp(normalize(distance_sqr, 0, self.m_range_sqr), 0, 1))
end

function interference:get_location_if_same_level(location_name)
    local location = nanosuit_utils.get_named_location(location_name)
    if simulation_objects.is_on_the_same_level(alife():actor(), { m_game_vertex_id = location.gvid }) then
        return location
    end
    return nil
end

