---==================================================================================================================---
---                                                                                                                  ---
---    Original Author(s) : NLTP_ASHES                                                                               ---
---    Edited : N/A                                                                                                  ---
---    Date : 08/02/2026                                                                                             ---
---    License : Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)           ---
---                                                                                                                  ---
---    Script used to handle the logic of an abstract suit mode of the Nanosuit addon.                               ---
---                                                                                                                  ---
---==================================================================================================================---

-- ---------------------------------------------------------------------------------------------------------------------
-- Constants, global variables and imported functions
-- ---------------------------------------------------------------------------------------------------------------------

localized_and_genderized_sound_object  = nanosuit_utils.localized_and_genderized_sound_object
actor_slots_enum                       = nanosuit_utils.actor_slots_enum
hit_types_enum                         = nanosuit_utils.hit_types_enum

-- ---------------------------------------------------------------------------------------------------------------------
-- Mode class
-- ---------------------------------------------------------------------------------------------------------------------

class "abstract_mode"

function abstract_mode:__init(core, name)
    self.m_core = core
    self.m_name = name
    self.m_sounds = {
        voice = localized_and_genderized_sound_object([[nanosuit\voice]], "mode_" .. name .. "_voice"),
    }
    self.m_cache = {}
    self.m_boosters = {}
    self.m_protection_map = {}
    
    for hit_name, hit_id in pairs(hit_types_enum) do
        self.m_protection_map[hit_id] = nanosuit_mcm.get_constant("protection_" .. name .. "_" .. hit_name, nil)
    end

    -- Register callbacks
    RegisterScriptCallback("on_option_change", self)
end

function abstract_mode:__eq(other)
    return self.m_name == other.m_name
end

function abstract_mode:destroy()
    self.m_core = nil

    -- Unregister callbacks
    UnregisterScriptCallback("on_option_change", self)
end

function abstract_mode:apply(play_voice)
    -- Register callbacks
    RegisterScriptCallback("on_before_hit_after_calcs", self)

    -- Play sounds
    if play_voice then
        self.m_sounds.voice:play_at_pos(db.actor, VEC_ZERO, 0, sound_object.s2d)
    end
end

function abstract_mode:remove(is_destroying)
    -- Unregister callbacks
    UnregisterScriptCallback("on_before_hit_after_calcs", self)
end

function abstract_mode:apply_booster(booster, name)
    if not self.m_boosters[name] then
        self.m_boosters[name] = booster(self.m_core, name)
        self.m_boosters[name]:apply()
    end
end

function abstract_mode:remove_booster(name)
    if self.m_boosters[name] then
        self.m_boosters[name]:remove()
        self.m_boosters[name]:destroy()
        self.m_boosters[name] = nil
    end
end

function abstract_mode:on_option_change()
    self.m_sounds.voice = localized_and_genderized_sound_object([[nanosuit\voice]], "mode_" .. self.m_name .. "_voice")
end

function abstract_mode:on_before_hit_after_calcs(scripted_hit, target, bone_id)
    -- Only apply to actor
    if target:id() ~= AC_ID then
        return
    end

    -- Get amount of damage suit can absorb (if any)
    local max_absorb_power = self.m_protection_map[scripted_hit.type]
    if not max_absorb_power then
        return
    end

    -- Calculate energy to use and damage to absorb
    local absorb_energy_req = scripted_hit.power / max_absorb_power * 100
    local absorb_energy_use = math.min(self.m_core.m_energy.m_level, absorb_energy_req)
    local absorb_power = absorb_energy_use / 100 * max_absorb_power

    -- Use energy
    self.m_core.m_energy:use_energy(absorb_energy_use)

    -- Absorb hit
    scripted_hit.power = scripted_hit.power - absorb_power

    if self.m_core.m_energy.m_level > 0 then
        -- Game is stupid and still registers damage sometimes even with power set to 0
        -- FIXME : on_before_hit_after_calcs doesn't support flags, see if this is still needed anyway
        -- flags.ret_value = false
    end
end