---==================================================================================================================---
---                                                                                                                  ---
---    Original Author(s) : NLTP_ASHES                                                                               ---
---    Edited : N/A                                                                                                  ---
---    Date : 03/09/2025                                                                                             ---
---    License : Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)           ---
---                                                                                                                  ---
---    Script used to handle the core logic of the Nanosuit addon.                                                   ---
---                                                                                                                  ---
---==================================================================================================================---

-- ---------------------------------------------------------------------------------------------------------------------
-- Constants, global variables and imported functions
-- ---------------------------------------------------------------------------------------------------------------------

-- ---------------------------------------------------------------------------------------------------------------------
-- Core class
-- ---------------------------------------------------------------------------------------------------------------------

class "energy"

function energy:__init()
    -- Variables
    self.m_level = 100
    self.m_last_use = 0
    self.m_last_regen = 0
    self.m_regen_rate = 100
    self.m_regen_delay = 5000
    self.m_regen_conditions = {}
    self.m_drains = {}

    -- Register callbacks
    RegisterScriptCallback("actor_on_update", self)

    self:add_regen_condition(function() return time_global() - self.m_last_use > self.m_regen_delay end)
end

function energy:destroy()
    self.m_regen_conditions = nil
    self.m_drains = nil

    UnregisterScriptCallback("actor_on_update", self)
end

function energy:use_energy(amount)
    self.m_level = clamp(self.m_level - amount, 0, 100)
    self.m_last_use = time_global()
end

function energy:regen_energy(amount)
    self.m_level = clamp(self.m_level + amount, 0, 100)
    self.m_last_regen = time_global()
end

function energy:add_regen_condition(condition)
    table.insert(self.m_regen_conditions, condition)
end

function energy:can_regen()
    for _, condition in pairs(self.m_regen_conditions) do
        if condition() == false then
            return false
        end
    end
    return true
end

function energy:has_drain(name)
    return self.m_drains[name] ~= nil
end

function energy:add_drain(name, freq, amount_or_func)
    printf("[NS] Energy | Adding drain '%s' (freq: %s, amount_or_func: %s)", name, freq, amount_or_func)
    self.m_drains[name] = { amount_or_func = amount_or_func, freq = freq, last_drain = 0 }
end

function energy:remove_drain(name)
    printf("[NS] Energy | Removing drain '%s'", name)
    self.m_drains[name] = nil
end

function energy:actor_on_update()
    for _, drain in pairs(self.m_drains) do
        if time_global() - drain.last_drain > drain.freq then
            local amount = type(drain.amount_or_func) == "function" and drain.amount_or_func() or drain.amount_or_func
            self:use_energy(amount)
            drain.last_drain = time_global()
        end
    end

    -- Energy regen
    if self:can_regen() and time_global() - self.m_last_regen > self.m_regen_rate then
        self:regen_energy(1)
    end
end
