---==================================================================================================================---
---                                                                                                                  ---
---    Original Author(s) : NLTP_ASHES                                                                               ---
---    Edited : N/A                                                                                                  ---
---    Date : 09/11/2025                                                                                             ---
---    License : Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)           ---
---                                                                                                                  ---
---    Script used to handle the Nanosuit's main HUD UI.                                                             ---
---                                                                                                                  ---
---==================================================================================================================---

-- ---------------------------------------------------------------------------------------------------------------------
-- Constants, global variables and imported functions
-- ---------------------------------------------------------------------------------------------------------------------

-- Imports
fire_modes_names_enum   = nanosuit_utils.fire_modes_names_enum
actor_cameras_enum      = nanosuit_utils.actor_cameras_enum

-- Variables
is_in_game              = false

-- ---------------------------------------------------------------------------------------------------------------------
-- General functions
-- ---------------------------------------------------------------------------------------------------------------------

function on_loading_screen_dismissed()
    is_in_game = true
end

-- ---------------------------------------------------------------------------------------------------------------------
-- Callbacks registration
-- ---------------------------------------------------------------------------------------------------------------------

--- Function used to register callbacks.
--- @return nil
function on_game_start()
    RegisterScriptCallback("on_loading_screen_dismissed", on_loading_screen_dismissed)
end

-- ---------------------------------------------------------------------------------------------------------------------
-- Main HUD UI class
-- ---------------------------------------------------------------------------------------------------------------------

class "ui_hud" (CUIScriptWnd)

function ui_hud:__init(core) super()
    self.m_core = core

    -- Variables
    self.m_next_update = time_global()
    self.m_update_rate = 1000
    self.m_set_msg_functor = nil
    self.m_colors = {
        text = nanosuit_mcm.get_constant("hud_colors_text", GetARGB(255, 129, 183, 135)),
        background = nanosuit_mcm.get_constant("hud_colors_background", GetARGB(200, 99, 125, 102)),
        active = GetARGB(200, 250, 173, 44),
        energy = nanosuit_mcm.get_constant("hud_colors_energy", GetARGB(255, 0, 107, 179)),
        energy_bg = GetARGB(200, 18, 40, 46),
        energy_off_bg = GetARGB(200, 24, 24, 24),
        health = nanosuit_mcm.get_constant("hud_colors_health", GetARGB(255, 85, 148, 17)),
        health_bg = GetARGB(200, 27, 33, 21),
        health_off_bg = GetARGB(200, 24, 24, 24),
        stamina = nanosuit_mcm.get_constant("hud_colors_stamina", GetARGB(255, 255, 255, 0)),
        stamina_bg = GetARGB(200, 46, 46, 24),
        stamina_off_bg = GetARGB(200, 24, 24, 24),
        nv_energy = GetARGB(255, 253, 254, 50),
        nv_energy_bg = GetARGB(200, 142, 155, 23),
        nv_energy_off_bg = GetARGB(200, 24, 24, 24),
        red = GetARGB(255, 255, 0, 0)
    }

    -- Build UI
    self.m_ui_menu = nanosuit_ui_menu.ui_menu(self)
    self:AttachChild(self.m_ui_menu)

    self.m_ui_status = nanosuit_ui_status.ui_status(self)
    self.m_ui_status:Show(true)
    self:AttachChild(self.m_ui_status)

    self.m_ui_tacmap = nanosuit_ui_tacmap.ui_tacmap(self)
    self.m_ui_tacmap:Show(true)
    self:AttachChild(self.m_ui_tacmap)

    self.m_ui_auxiliaries = nanosuit_ui_auxiliaries.ui_auxiliaries(self)
    self.m_ui_auxiliaries:Show(true)
    self:AttachChild(self.m_ui_auxiliaries)

    self.m_ui_indicators = nanosuit_ui_indicators.ui_indicators(self)
    self.m_ui_indicators:Show(true)
    self:AttachChild(self.m_ui_indicators)

    self.m_ui_defibrillator = nanosuit_ui_defibrillator.ui_defibrillator(self)
    self:AttachChild(self.m_ui_defibrillator)

    self:Show(false)

    -- Register callbacks
    RegisterScriptCallback("actor_on_update", self)
    RegisterScriptCallback("on_loading_screen_dismissed", self)

    if is_in_game then
        -- Switch to custom HUD
        self:switch_hud(true)
    end
end

function ui_hud:__finalize()
end

function ui_hud:destroy()
    -- Switch to default HUD
    self:switch_hud(false)

    -- Destroy children
    self.m_ui_menu:destroy()
    self.m_ui_status:destroy()
    self.m_ui_tacmap:destroy()
    self.m_ui_auxiliaries:destroy()
    self.m_ui_indicators:destroy()
    self.m_ui_defibrillator:destroy()

    self.m_core = nil

    -- Unregister callbacks
    UnregisterScriptCallback("actor_on_update", self)
    UnregisterScriptCallback("on_loading_screen_dismissed", self)
end

function ui_hud:switch_hud(take_control)
    -- Get main HUD
    local hud = get_hud()
    local main_hud = ActorMenu.get_maingame()

    if take_control then
        -- Attach to main HUD
        hud:AddDialogToRender(self)

        -- Remove PDA icon
        self:remove_pda_icon()

        self.m_set_msg_functor = actor_menu.set_msg
        actor_menu.set_msg = function(...)
            local res = self.m_set_msg_functor(...)
            self:remove_pda_icon()
            return res
        end

        self.m_set_notification_functor = actor_menu.set_notification
        actor_menu.set_notification = function(...)
            local res = self.m_set_notification_functor(...)
            self:remove_pda_icon()
            return res
        end

        -- Hide minimap
        main_hud.UIZoneMap.disabled = true
        main_hud.UIMotionIcon:Show(false)
    else
        -- Detach from main HUD
        hud:RemoveDialogToRender(self)

        -- Restore PDA icon
        actor_menu.set_msg = self.m_set_msg_functor
        self.m_set_msg_functor = nil

        actor_menu.set_notification = self.m_set_notification_functor
        self.m_set_notification_functor = nil

        -- Show minimap
        main_hud.UIZoneMap.disabled = not ui_options.get([[video/hud/show_minimap]])
        main_hud.UIMotionIcon:Show(not main_hud.UIZoneMap.disabled)
    end

    local elements_to_move = self:get_elements_to_move()

    -- Move elements
    for _, element in ipairs(elements_to_move) do
        if element.element then
            local pos = element.element:GetWndPos()
            local offset_x, offset_y = nil, nil
            if element.hide then
                offset_x = -device().width - element.element:GetWidth()
                offset_y = 0
            else
                offset_x = element.x or 0
                offset_y = element.y or 0
            end
            pos.x = pos.x + (take_control and offset_x or -offset_x)
            pos.y = pos.y + (take_control and offset_y or -offset_y)
            element.element:SetWndPos(pos)
        end
    end
end

function ui_hud:get_elements_to_move()
    local main_hud = ActorMenu.get_maingame()

    local elements_to_move = {
        { element = ActorMenu.get_messages_menu(), y = -100 },
        { element = actor_status.HUD, hide = true },
        { element = main_hud.m_ui_hud_states.m_ui_weapon_icon, hide = true },
        { element = main_hud.m_ui_hud_states.m_ui_weapon_cur_ammo, hide = true },
        { element = main_hud.m_ui_hud_states.m_ui_grenade, hide = true },
        { element = main_hud.m_ui_hud_states.m_fire_mode, hide = true },
        { element = main_hud.m_ui_hud_states.m_ui_health_bar, hide = true },
        { element = main_hud.m_ui_hud_states.m_ui_stamina_bar, hide = true },
        { element = main_hud.m_ui_hud_states.m_ui_psy_bar, hide = true },
        { element = main_hud.m_ui_hud_states.m_back, hide = true },
        { element = main_hud.m_QuickSlotText1, hide = true },
        { element = main_hud.m_QuickSlotText2, hide = true },
        { element = main_hud.m_QuickSlotText3, hide = true },
        { element = main_hud.m_QuickSlotText4, hide = true }
    }

    for _, elem in pairs(main_hud:GetQuickSlotIcons()) do
        table.insert(elements_to_move, { element = elem, hide = true })
    end

    -- Patch for Faction ID mod
    if factionid_hud_mcm and factionid_hud_mcm.HUD then
        table.insert(elements_to_move, { element = factionid_hud_mcm.HUD, x = 115 })
    end

    return elements_to_move
end

function ui_hud:on_loading_screen_dismissed()
    self:switch_hud(true)
end

function ui_hud:actor_on_update()
    self:Update(true)
end

function ui_hud:Update(force)
    CUIScriptWnd.Update(self)

    local tg = time_global()

    -- Force update
    if force then
        self.m_next_update = tg - 1
    end

    -- Throttle update
    if self.m_next_update >= tg then
        return
    else
        self.m_next_update = tg + self.m_update_rate
    end

    -- Handle UI visibility
    local should_show = (main_hud_shown() or self.m_ui_menu:IsShown()) and (db.actor:alive() or level.get_active_cam() == actor_cameras_enum.first_eye)

    if not should_show and self:IsShown() then
        self:Show(false)
    elseif should_show and not self:IsShown() then
        self:Show(true)
    end

    -- Update children
    self.m_ui_menu:Update(force)
    self.m_ui_status:Update(force)
    self.m_ui_tacmap:Update(force)
    self.m_ui_auxiliaries:Update(force)
    self.m_ui_indicators:Update(force)
    self.m_ui_defibrillator:Update(force)
end

function ui_hud:remove_pda_icon()
    local hud = get_hud()
    if hud and hud:GetCustomStatic("notify_icon") then
        -- Lil shit
        hud:RemoveCustomStatic("notify_icon")
    end
end
