---==================================================================================================================---
---                                                                                                                  ---
---    Original Author(s) : NLTP_ASHES                                                                               ---
---    Edited : N/A                                                                                                  ---
---    Date : 02/08/2026                                                                                             ---
---    License : Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)           ---
---                                                                                                                  ---
---    Script used to handle the Nanosuit status hub (energy, health, ammo, etc) UI.                                 ---
---                                                                                                                  ---
---==================================================================================================================---

-- ---------------------------------------------------------------------------------------------------------------------
-- Constants, global variables and imported functions
-- ---------------------------------------------------------------------------------------------------------------------

-- Imports
fire_modes_names_enum  = nanosuit_utils.fire_modes_names_enum

-- ---------------------------------------------------------------------------------------------------------------------
-- Status UI class
-- ---------------------------------------------------------------------------------------------------------------------

class "ui_status" (CUIScriptWnd)

function ui_status:__init(parent) super()
    -- Variables
    self.m_parent = parent
    self.m_ammo_count_low_threshold = 0.2
    self.m_ammo_reserve_low_threshold = 0

    -- Build UI
    self.m_xml = CScriptXmlInit()
    self.m_xml:ParseFile("ui_nanosuit_status.xml")

    self.m_ui_background = self.m_xml:InitStatic("background", self)
    arm.scale_ui(self.m_ui_background, true, true, "right")

    self.m_ui_outline = self.m_xml:InitStatic("outline", self)
    self.m_ui_outline:SetTextureColor(self.m_parent.m_colors.background)
    arm.scale_ui(self.m_ui_outline, true, true, "right")

    self.m_ui_suit_mode = self.m_xml:InitStatic("suit_mode", self)
    self.m_ui_suit_mode:SetTextureColor(self.m_parent.m_colors.background)
    arm.scale_ui(self.m_ui_suit_mode, true, true, "right")

    self.m_ui_energy = self.m_xml:InitTextWnd("energy", self)
    self.m_ui_energy:SetTextColor(self.m_parent.m_colors.text)
    arm.scale_ui(self.m_ui_energy, true, true, "right")

    self.m_ui_energy_bar_background = self.m_xml:InitStatic("energy_bar_background", self)
    self.m_ui_energy_bar_background:SetTextureColor(self.m_parent.m_colors.energy_bg)
    arm.scale_ui(self.m_ui_energy_bar_background, true, true, "right")

    self.m_ui_energy_bar = self.m_xml:InitProgressBar("energy_bar", self)
    arm.scale_ui(self.m_ui_energy_bar, true, true, "right")
    arm.scale_ui(self.m_ui_energy_bar:GetProgressStatic(), true, true, "left", self.m_ui_energy_bar:GetWidth())

    self.m_ui_energy_icon = self.m_xml:InitStatic("energy_icon", self)
    self.m_ui_energy_icon:SetTextureColor(self.m_parent.m_colors.text)
    arm.scale_ui(self.m_ui_energy_icon, true, true, "right")

    self.m_ui_health = self.m_xml:InitTextWnd("health", self)
    self.m_ui_health:SetTextColor(self.m_parent.m_colors.text)
    arm.scale_ui(self.m_ui_health, true, true, "right")

    self.m_ui_health_bar_background = self.m_xml:InitStatic("health_bar_background", self)
    self.m_ui_health_bar_background:SetTextureColor(self.m_parent.m_colors.health_bg)
    arm.scale_ui(self.m_ui_health_bar_background, true, true, "right")

    self.m_ui_health_bar = self.m_xml:InitProgressBar("health_bar", self)
    arm.scale_ui(self.m_ui_health_bar, true, true, "right")
    arm.scale_ui(self.m_ui_health_bar:GetProgressStatic(), true, true, "left", self.m_ui_health_bar:GetWidth())

    self.m_ui_health_icon = self.m_xml:InitStatic("health_icon", self)
    self.m_ui_health_icon:SetTextureColor(self.m_parent.m_colors.text)
    arm.scale_ui(self.m_ui_health_icon, true, true, "right")

    self.m_ui_stamina = self.m_xml:InitTextWnd("stamina", self)
    self.m_ui_stamina:SetTextColor(self.m_parent.m_colors.text)
    arm.scale_ui(self.m_ui_stamina, true, true, "right")

    self.m_ui_stamina_bar_background = self.m_xml:InitStatic("stamina_bar_background", self)
    self.m_ui_stamina_bar_background:SetTextureColor(self.m_parent.m_colors.stamina_bg)
    arm.scale_ui(self.m_ui_stamina_bar_background, true, true, "right")

    self.m_ui_stamina_bar = self.m_xml:InitProgressBar("stamina_bar", self)
    arm.scale_ui(self.m_ui_stamina_bar, true, true, "right")
    arm.scale_ui(self.m_ui_stamina_bar:GetProgressStatic(), true, true, "left", self.m_ui_stamina_bar:GetWidth())

    self.m_ui_stamina_icon = self.m_xml:InitStatic("stamina_icon", self)
    self.m_ui_stamina_icon:SetTextureColor(self.m_parent.m_colors.text)
    arm.scale_ui(self.m_ui_stamina_icon, true, true, "right")

    self.m_ui_ammo_count = self.m_xml:InitTextWnd("ammo_count", self)
    self.m_ui_ammo_count:SetTextColor(self.m_parent.m_colors.text)
    arm.scale_ui(self.m_ui_ammo_count, true, true, "right")

    self.m_ui_ammo_reserve = self.m_xml:InitTextWnd("ammo_reserve", self)
    self.m_ui_ammo_reserve:SetTextColor(self.m_parent.m_colors.text)
    arm.scale_ui(self.m_ui_ammo_reserve, true, true, "right")

    self.m_ui_fire_mode = self.m_xml:InitStatic("fire_mode", self)
    self.m_ui_fire_mode:SetTextureColor(self.m_parent.m_colors.background)
    arm.scale_ui(self.m_ui_fire_mode, true, true, "right")
end

function ui_status:__finalize()
end

function ui_status:destroy()
end

function ui_status:Update(force)
    CUIScriptWnd.Update(self)

    if self.m_parent.m_core.m_malfunctor.m_enabled then
        self:update_in_malfunction()
        return
    end

    self:update_outline()
    self:update_suit_mode()
    self:update_energy()
    self:update_health()
    self:update_stamina()

    local active_item = db.actor:active_item()
    local weapon_obj = active_item and IsWeapon(active_item) and not IsMelee(active_item) and active_item
    local weapon_class = weapon_obj and weapon_obj:cast_Weapon()

    self:update_ammo_count(weapon_obj, weapon_class)
    self:update_ammo_reserve(weapon_obj, weapon_class)
    self:update_fire_mode(weapon_obj, weapon_class)
end

function ui_status:update_in_malfunction()
    -- Outline
    self.m_ui_outline:SetTextureColor(self.m_parent.m_colors.red)

    -- Current suit mode
    self.m_ui_suit_mode:SetTextureColor(self.m_parent.m_colors.red)
    self.m_ui_suit_mode:InitTexture("ui_nanosuit_no_draw")

    -- Energy
    self.m_ui_energy:SetText("!")
    self.m_ui_energy:SetTextColor(self.m_parent.m_colors.red)
    self.m_ui_energy_bar:SetProgressPos(0)
    self.m_ui_energy_bar_background:SetTextureColor(self.m_parent.m_colors.energy_off_bg)
    self.m_ui_energy_icon:SetTextureColor(self.m_parent.m_colors.red)

    -- Health
    self.m_ui_health:SetText("!")
    self.m_ui_health:SetTextColor(self.m_parent.m_colors.red)
    self.m_ui_health_bar:SetProgressPos(0)
    self.m_ui_health_bar_background:SetTextureColor(self.m_parent.m_colors.health_off_bg)
    self.m_ui_health_icon:SetTextureColor(self.m_parent.m_colors.red)

    -- Stamina
    self.m_ui_stamina:SetText("!")
    self.m_ui_stamina:SetTextColor(self.m_parent.m_colors.red)
    self.m_ui_stamina_bar:SetProgressPos(0)
    self.m_ui_stamina_bar_background:SetTextureColor(self.m_parent.m_colors.stamina_off_bg)
    self.m_ui_stamina_icon:SetTextureColor(self.m_parent.m_colors.red)

    -- Ammo count
    self.m_ui_ammo_count:SetText("")

    -- Ammo reserve
    self.m_ui_ammo_reserve:SetText("")

    -- Fire mode
    self.m_ui_fire_mode:InitTexture("ui_nanosuit_no_draw")
end

function ui_status:update_outline()
    self.m_ui_outline:SetTextureColor(self.m_parent.m_colors.background)
end

function ui_status:update_suit_mode()
    local suit_mode = "ui_nanosuit_status_" .. self.m_parent.m_core.m_current_mode.m_name
    self.m_ui_suit_mode:InitTexture(suit_mode)
    self.m_ui_suit_mode:SetTextureColor(self.m_parent.m_colors.background)
end

function ui_status:update_energy()
    local energy = self.m_parent.m_core.m_energy.m_level
    energy = round(energy)
    energy = clamp(energy, 0, 100)
    self.m_ui_energy_bar:SetColor(energy > 20 and self.m_parent.m_colors.energy or self.m_parent.m_colors.red)
    self.m_ui_energy_bar:SetProgressPos(energy)
    self.m_ui_energy_bar_background:SetTextureColor(self.m_parent.m_colors.energy_bg)
    energy = tostring(energy)
    self.m_ui_energy:SetText(energy)
    self.m_ui_energy:SetTextColor(self.m_parent.m_colors.text)
    self.m_ui_energy_icon:SetTextureColor(self.m_parent.m_colors.text)
end

function ui_status:update_health()
    local health = db.actor.health
    health = health * 100
    health = round(health)
    health = clamp(health, 0, 100)
    self.m_ui_health_bar:SetColor(health > 20 and self.m_parent.m_colors.health or self.m_parent.m_colors.red)
    self.m_ui_health_bar:SetProgressPos(health)
    self.m_ui_health_bar_background:SetTextureColor(self.m_parent.m_colors.health_bg)
    health = tostring(health)
    self.m_ui_health:SetText(health)
    self.m_ui_health:SetTextColor(self.m_parent.m_colors.text)
    self.m_ui_health_icon:SetTextureColor(self.m_parent.m_colors.text)
end

function ui_status:update_stamina()
    local stamina = db.actor.power
    stamina = stamina * 100
    stamina = round(stamina)
    stamina = clamp(stamina, 0, 100)
    self.m_ui_stamina_bar:SetColor(stamina > 20 and self.m_parent.m_colors.stamina or self.m_parent.m_colors.red)
    self.m_ui_stamina_bar:SetProgressPos(stamina)
    self.m_ui_stamina_bar_background:SetTextureColor(self.m_parent.m_colors.stamina_bg)
    stamina = tostring(stamina)
    self.m_ui_stamina:SetText(stamina)
    self.m_ui_stamina:SetTextColor(self.m_parent.m_colors.text)
    self.m_ui_stamina_icon:SetTextureColor(self.m_parent.m_colors.text)
end

function ui_status:update_ammo_count(weapon_obj, weapon_class)
    if not weapon_obj or not weapon_class then
        self.m_ui_ammo_count:SetText("---")
        self.m_ui_ammo_count:SetTextColor(self.m_parent.m_colors.text)
        return
    end

    local ammo = weapon_obj:get_ammo_in_magazine()
    local mag_size = weapon_class:GetAmmoMagSize()

    if ammo <= mag_size * self.m_ammo_count_low_threshold then
        self.m_ui_ammo_count:SetTextColor(self.m_parent.m_colors.red)
    else
        self.m_ui_ammo_count:SetTextColor(self.m_parent.m_colors.text)
    end

    ammo = clamp(ammo, 0, 999)
    ammo = tostring(ammo)
    ammo = nanosuit_utils.string_pad_l(ammo, "0", 3)
    self.m_ui_ammo_count:SetText(ammo)
end

function ui_status:update_ammo_reserve(weapon_obj, weapon_class)
    if not weapon_obj or not weapon_class then
        self.m_ui_ammo_reserve:SetText("---")
        self.m_ui_ammo_reserve:SetTextColor(self.m_parent.m_colors.text)
        return
    end

    local ammo_reserve = weapon_obj:get_ammo_count_for_type(weapon_obj:get_ammo_type())
    local mag_size = weapon_class:GetAmmoMagSize()

    if ammo_reserve <= mag_size * self.m_ammo_reserve_low_threshold then
        self.m_ui_ammo_reserve:SetTextColor(self.m_parent.m_colors.red)
    else
        self.m_ui_ammo_reserve:SetTextColor(self.m_parent.m_colors.text)
    end

    ammo_reserve = clamp(ammo_reserve, 0, 999)
    ammo_reserve = tostring(ammo_reserve)
    ammo_reserve = nanosuit_utils.string_pad_l(ammo_reserve, "0", 3)
    self.m_ui_ammo_reserve:SetText(ammo_reserve)
end

function ui_status:update_fire_mode(weapon_obj, weapon_class)
    if not weapon_obj or not weapon_class then
        self.m_ui_fire_mode:InitTexture("ui_nanosuit_no_draw")
        return
    end

    local fire_mode = weapon_class:GetFireMode()
    fire_mode = fire_modes_names_enum[fire_mode]
    fire_mode = "ui_nanosuit_status_" .. fire_mode
    self.m_ui_fire_mode:InitTexture(fire_mode)
end
