---==================================================================================================================---
---                                                                                                                  ---
---    Original Author(s) : NLTP_ASHES                                                                               ---
---    Edited : N/A                                                                                                  ---
---    Date : 31/08/2025                                                                                             ---
---    License : Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)           ---
---                                                                                                                  ---
---    Script used to handle the core logic of the Nanosuit addon.                                                   ---
---                                                                                                                  ---
---==================================================================================================================---

-- ---------------------------------------------------------------------------------------------------------------------
-- Constants, global variables and imported functions
-- ---------------------------------------------------------------------------------------------------------------------

-- ---------------------------------------------------------------------------------------------------------------------
-- Core class
-- ---------------------------------------------------------------------------------------------------------------------

class "energy"

function energy:__init()
    -- Variables
    self.m_level = 100
    self.m_last_use = 0
    self.m_last_regen = 0
    self.m_regen_rate = 100
    self.m_regen_delay = 5000
    self.m_regen_conditions = {}

    -- Register callbacks
    RegisterScriptCallback("actor_on_update", self)

    self:add_regen_condition(function() return time_global() - self.m_last_use > self.m_regen_delay end)
end

function energy:destroy()
    UnregisterScriptCallback("actor_on_update", self)
end

function energy:use_energy(amount)
    self.m_level = clamp(self.m_level - amount, 0, 100)
    self.m_last_use = time_global()
end

function energy:regen_energy(amount)
    self.m_level = clamp(self.m_level + amount, 0, 100)
    self.m_last_regen = time_global()
end

function energy:add_regen_condition(condition)
    table.insert(self.m_regen_conditions, condition)
end

function energy:can_regen()
    for _, condition in pairs(self.m_regen_conditions) do
        if condition() == false then
            return false
        end
    end
    return true
end

function energy:actor_on_update()
    if not self:can_regen() then
        return
    end

    if time_global() - self.m_last_regen > self.m_regen_rate then
        self:regen_energy(1)
    end
end
