---==================================================================================================================---
---                                                                                                                  ---
---    Original Author(s) : NLTP_ASHES                                                                               ---
---    Edited : N/A                                                                                                  ---
---    Date : 27/06/2025                                                                                             ---
---    License : Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)           ---
---                                                                                                                  ---
---    Script used to handle the malfunction logic of the Nanosuit addon.                                            ---
---                                                                                                                  ---
---==================================================================================================================---

-- ---------------------------------------------------------------------------------------------------------------------
-- Constants, global variables and imported functions
-- ---------------------------------------------------------------------------------------------------------------------

-- Imports
armor_modes_enum        = nanosuit_utils.armor_modes_enum

-- ---------------------------------------------------------------------------------------------------------------------
-- Malfunction class
-- ---------------------------------------------------------------------------------------------------------------------

class "malfunctor"

function malfunctor:__init(core)
    -- Constants
    self.m_core = core
    self.m_anomaly_hit_duration = 20

    -- Variables
    self.m_enabled = false
    self.m_stay_off = false

    -- Register callbacks
    RegisterScriptCallback("actor_on_death", self)
    RegisterScriptCallback("actor_on_interaction", self)
end

function malfunctor:destroy()
    -- Unregister callbacks
    UnregisterScriptCallback("actor_on_death", self)
    UnregisterScriptCallback("actor_on_interaction", self)
end

function malfunctor:save()
    return {
        enabled = self.m_enabled,
        stay_off = self.m_stay_off
    }
end

function malfunctor:load(m_data)
    self.m_stay_off = m_data.stay_off or false

    if m_data.enabled and not m_data.stay_off then
        self:enable_malfunction(m_data.stay_off)
    end
end

function malfunctor:enable_malfunction(stay_off)
    if not self.m_enabled then
        self.m_enabled = true
        self.m_stay_off = stay_off or false

        self.m_core:change_mode(armor_modes_enum.armor, false)
        self.m_core:use_energy(100)

        if not self.m_stay_off then
            CreateTimeEvent("nanosuit_malfunction", "disable", self.m_anomaly_hit_duration, function()
                self:disable_malfunction()
                return true
            end)
        end
    end
end

function malfunctor:disable_malfunction()
    if self.m_enabled then
        self.m_enabled = false
        self.m_core:change_mode(self.m_core.m_default_mode, true)
        self.m_core.m_energy_last_use = time_global()
    end
end

function malfunctor:actor_on_interaction(typ, obj, name)
    if typ == "anomalies" and name == "pulse" then
        self:enable_malfunction(false)
    end
end

function malfunctor:actor_on_death()
    self:enable_malfunction(true)
end
