---==================================================================================================================---
---                                                                                                                  ---
---    Original Author(s) : RavenAscendant                                                                           ---
---    Edited : NLTP_ASHES                                                                                           ---
---    Date : 21/09/2026                                                                                             ---
---    License : Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)           ---
---                                                                                                                  ---
---    Script used to define the options in MCM.                                                                     ---
---                                                                                                                  ---
---    If you do not have MCM installed, you can directly modify the values in the 'defaults' table just bellow.     ---
---    Note that editing that table will require you to reload your save before changes can take effect.             ---
---                                                                                                                  ---
---==================================================================================================================---

-- ---------------------------------------------------------------------------------------------------------------------
-- Constants, global variables and imported functions
-- ---------------------------------------------------------------------------------------------------------------------

-- Imports
mcm_types_enum                      = nanosuit_utils.mcm_types_enum
actor_slots_enum                    = nanosuit_utils.actor_slots_enum
gender_enum                         = nanosuit_utils.gender_enum
vision_perk_enum                    = nanosuit_utils.vision_perk_enum
themes_enum                         = nanosuit_utils.themes_enum

-- If you don't use MCM, change your defaults from here.
defaults = {
    -- General
    ["use_witness"] = false,
    ["suit_gender"] = gender_enum.male,
    ["customize_ammo_wheel"] = true,
    ["customize_companion_wheel"] = true,
    ["customize_companion_list"] = true,
    -- Keybindings
    ["defibrillate"] = DIK_keys.DIK_SPACE,
    ["suit_menu"] = DIK_keys.DIK_V,
    ["nanovision"] = DIK_keys.DIK_N,
    ["nightvision"] = DIK_keys.DIK_N,
    ["binoculars"] = DIK_keys.DIK_B,
    -- Configuration
    -- Nanosuit 1.0
    ["outfit_nanosuit/energy_use_factor"] = 1.0,
    ["outfit_nanosuit/energy_regen_factor"] = 1.0,
    ["outfit_nanosuit/vision_perk"] = vision_perk_enum.nightvision,
    ["outfit_nanosuit/theme"] = themes_enum.nanosuit_1,
    ["outfit_nanosuit/protection_armor_burn"] = 5.0,
    ["outfit_nanosuit/protection_armor_shock"] = 1.0,
    ["outfit_nanosuit/protection_armor_chemical_burn"] = 2.0,
    ["outfit_nanosuit/protection_armor_radiation"] = 0.5,
    ["outfit_nanosuit/protection_armor_wound"] = 0.7,
    ["outfit_nanosuit/protection_armor_fire_wound"] = 0.7,
    ["outfit_nanosuit/protection_armor_strike"] = 2.0,
    ["outfit_nanosuit/protection_armor_explosion"] = 0.4,
    ["outfit_nanosuit/protection_armor_wound_2"] = 0.4,
    ["outfit_nanosuit/protection_armor_light_burn"] = 5.0,
    ["outfit_nanosuit/protection_cloak_radiation"] = 0.5,
    ["outfit_nanosuit/protection_power_radiation"] = 0.5,
    ["outfit_nanosuit/protection_power_strike"] = 0.5,
    ["outfit_nanosuit/protection_speed_radiation"] = 0.5,
    -- Nanosuit 2.0
    ["outfit_nanosuit_2/energy_use_factor"] = 0.8,
    ["outfit_nanosuit_2/energy_regen_factor"] = 1.2,
    ["outfit_nanosuit_2/vision_perk"] = vision_perk_enum.nanovision,
    ["outfit_nanosuit_2/theme"] = themes_enum.nanosuit_2,
    ["outfit_nanosuit_2/protection_armor_burn"] = 5.0,
    ["outfit_nanosuit_2/protection_armor_shock"] = 1.0,
    ["outfit_nanosuit_2/protection_armor_chemical_burn"] = 2.0,
    ["outfit_nanosuit_2/protection_armor_radiation"] = 0.5,
    ["outfit_nanosuit_2/protection_armor_wound"] = 0.8,
    ["outfit_nanosuit_2/protection_armor_fire_wound"] = 0.8,
    ["outfit_nanosuit_2/protection_armor_strike"] = 2.0,
    ["outfit_nanosuit_2/protection_armor_explosion"] = 0.4,
    ["outfit_nanosuit_2/protection_armor_wound_2"] = 0.4,
    ["outfit_nanosuit_2/protection_armor_light_burn"] = 5.0,
    ["outfit_nanosuit_2/protection_cloak_radiation"] = 0.5,
    ["outfit_nanosuit_2/protection_power_radiation"] = 0.5,
    ["outfit_nanosuit_2/protection_power_strike"] = 0.5,
    ["outfit_nanosuit_2/protection_speed_radiation"] = 0.5,
    -- Korean Nanosuit
    ["outfit_nanosuit_asian/energy_use_factor"] = 1.0,
    ["outfit_nanosuit_asian/energy_regen_factor"] = 0.9,
    ["outfit_nanosuit_asian/vision_perk"] = vision_perk_enum.nightvision,
    ["outfit_nanosuit_asian/theme"] = themes_enum.nanosuit_korean,
    ["outfit_nanosuit_asian/protection_armor_burn"] = 5.0,
    ["outfit_nanosuit_asian/protection_armor_shock"] = 1.0,
    ["outfit_nanosuit_asian/protection_armor_chemical_burn"] = 2.0,
    ["outfit_nanosuit_asian/protection_armor_radiation"] = 0.5,
    ["outfit_nanosuit_asian/protection_armor_wound"] = 0.7,
    ["outfit_nanosuit_asian/protection_armor_fire_wound"] = 0.5,
    ["outfit_nanosuit_asian/protection_armor_strike"] = 2.0,
    ["outfit_nanosuit_asian/protection_armor_explosion"] = 0.4,
    ["outfit_nanosuit_asian/protection_armor_wound_2"] = 0.4,
    ["outfit_nanosuit_asian/protection_armor_light_burn"] = 5.0,
    ["outfit_nanosuit_asian/protection_cloak_radiation"] = 0.5,
    ["outfit_nanosuit_asian/protection_power_radiation"] = 0.5,
    ["outfit_nanosuit_asian/protection_power_strike"] = 0.5,
    ["outfit_nanosuit_asian/protection_speed_radiation"] = 0.5,
    -- HUD/UI themes
    -- nanosuit_1 theme, General
    ["nanosuit_1/text"] = "255,129,183,135",
    ["nanosuit_1/outline"] = "200,99,125,102",
    ["nanosuit_1/accent"] = "200,250,173,44",
    ["nanosuit_1/alert"] = "255,255,0,0",
    ["nanosuit_1/background"] = "200,255,255,255",
    -- nanosuit_1 theme, Status UI
    ["nanosuit_1/status_energy"] = "255,0,145,189",
    ["nanosuit_1/status_energy_bg"] = "200,18,40,46",
    ["nanosuit_1/status_energy_off_bg"] = "200,24,24,24",
    ["nanosuit_1/status_health"] = "255,85,148,17",
    ["nanosuit_1/status_health_bg"] = "200,27,33,21",
    ["nanosuit_1/status_health_off_bg"] = "200,24,24,24",
    ["nanosuit_1/status_stamina"] = "255,255,255,0",
    ["nanosuit_1/status_stamina_bg"] = "200,46,46,24",
    ["nanosuit_1/status_stamina_off_bg"] = "200,24,24,24",
    -- nanosuit_1 theme, Tactical map UI
    ["nanosuit_1/tacmap_map"] = "127,255,255,255",
    ["nanosuit_1/tacmap_visibility_bg"] = "200,100,100,100",
    ["nanosuit_1/tacmap_visibility_very_low"] = "255,0,255,0",
    ["nanosuit_1/tacmap_visibility_low"] = "255,255,192,0",
    ["nanosuit_1/tacmap_visibility_high"] = "255,255,128,0",
    ["nanosuit_1/tacmap_visibility_very_high"] = "255,255,0,0",
    ["nanosuit_1/tacmap_icon_default"] = "255,255,255,255",
    ["nanosuit_1/tacmap_icon_looted"] = "255,150,150,150",
    ["nanosuit_1/tacmap_icon_friend"] = "255,0,255,0",
    ["nanosuit_1/tacmap_icon_neutral"] = "255,255,255,0",
    ["nanosuit_1/tacmap_icon_enemy"] = "255,255,0,0",
    ["nanosuit_1/tacmap_icon_primary_task"] = "255,0,255,0",
    ["nanosuit_1/tacmap_icon_secondary_task"] = "255,255,255,0",
    -- nanosuit_1 theme, Auxiliaries UI
    ["nanosuit_1/auxiliaries_nv_energy"] = "255,253,254,50",
    ["nanosuit_1/auxiliaries_nv_energy_bg"] = "200,142,155,23",
    ["nanosuit_1/auxiliaries_nv_energy_off_bg"] = "200,24,24,24",
    -- nanosuit_1 theme, Indicators UI
    ["nanosuit_1/indicators_warning_low"] = "255,255,255,50",
    ["nanosuit_1/indicators_warning_medium"] = "255,255,125,50",
    ["nanosuit_1/indicators_warning_high"] = "255,255,50,50",
    -- nanosuit_korean theme, General
    ["nanosuit_korean/text"] = "255,142,142,117",
    ["nanosuit_korean/outline"] = "200,125,125,102",
    ["nanosuit_korean/accent"] = "200,250,173,44",
    ["nanosuit_korean/alert"] = "255,255,0,0",
    ["nanosuit_korean/background"] = "200,255,255,255",
    -- nanosuit_korean theme, Status UI
    ["nanosuit_korean/status_energy"] = "255,0,59,99",
    ["nanosuit_korean/status_energy_bg"] = "200,18,40,46",
    ["nanosuit_korean/status_energy_off_bg"] = "200,24,24,24",
    ["nanosuit_korean/status_health"] = "255,75,100,60",
    ["nanosuit_korean/status_health_bg"] = "200,27,33,21",
    ["nanosuit_korean/status_health_off_bg"] = "200,24,24,24",
    ["nanosuit_korean/status_stamina"] = "255,100,100,0",
    ["nanosuit_korean/status_stamina_bg"] = "200,46,46,24",
    ["nanosuit_korean/status_stamina_off_bg"] = "200,24,24,24",
    -- nanosuit_korean theme, Tactical map UI
    ["nanosuit_korean/tacmap_map"] = "127,255,255,255",
    ["nanosuit_korean/tacmap_visibility_bg"] = "200,100,100,100",
    ["nanosuit_korean/tacmap_visibility_very_low"] = "255,0,255,0",
    ["nanosuit_korean/tacmap_visibility_low"] = "255,255,192,0",
    ["nanosuit_korean/tacmap_visibility_high"] = "255,255,128,0",
    ["nanosuit_korean/tacmap_visibility_very_high"] = "255,255,0,0",
    ["nanosuit_korean/tacmap_icon_default"] = "255,255,255,255",
    ["nanosuit_korean/tacmap_icon_looted"] = "255,150,150,150",
    ["nanosuit_korean/tacmap_icon_friend"] = "255,0,255,0",
    ["nanosuit_korean/tacmap_icon_neutral"] = "255,255,255,0",
    ["nanosuit_korean/tacmap_icon_enemy"] = "255,255,0,0",
    ["nanosuit_korean/tacmap_icon_primary_task"] = "255,0,255,0",
    ["nanosuit_korean/tacmap_icon_secondary_task"] = "255,255,255,0",
    -- nanosuit_korean theme, Auxiliaries UI
    ["nanosuit_korean/auxiliaries_nv_energy"] = "255,253,254,50",
    ["nanosuit_korean/auxiliaries_nv_energy_bg"] = "200,142,155,23",
    ["nanosuit_korean/auxiliaries_nv_energy_off_bg"] = "200,24,24,24",
    -- nanosuit_korean theme, Indicators UI
    ["nanosuit_korean/indicators_warning_low"] = "255,255,255,50",
    ["nanosuit_korean/indicators_warning_medium"] = "255,255,125,50",
    ["nanosuit_korean/indicators_warning_high"] = "255,255,50,50",
    -- nanosuit_2 theme, General
    ["nanosuit_2/text"] = "255,226,255,228",
    ["nanosuit_2/outline"] = "200,210,255,210",
    ["nanosuit_2/accent"] = "200,250,173,44",
    ["nanosuit_2/alert"] = "255,255,0,0",
    ["nanosuit_2/background"] = "200,255,255,255",
    -- nanosuit_2 theme, Status UI
    ["nanosuit_2/status_energy"] = "255,210,255,210",
    ["nanosuit_2/status_energy_bg"] = "200,18,40,46",
    ["nanosuit_2/status_energy_off_bg"] = "200,24,24,24",
    ["nanosuit_2/status_health"] = "255,210,255,210",
    ["nanosuit_2/status_health_bg"] = "200,27,33,21",
    ["nanosuit_2/status_health_off_bg"] = "200,24,24,24",
    ["nanosuit_2/status_stamina"] = "255,210,255,210",
    ["nanosuit_2/status_stamina_bg"] = "200,46,46,24",
    ["nanosuit_2/status_stamina_off_bg"] = "200,24,24,24",
    -- nanosuit_2 theme, Tactical map UI
    ["nanosuit_2/tacmap_map"] = "127,255,255,255",
    ["nanosuit_2/tacmap_visibility_bg"] = "200,100,100,100",
    ["nanosuit_2/tacmap_visibility_very_low"] = "255,0,255,0",
    ["nanosuit_2/tacmap_visibility_low"] = "255,255,192,0",
    ["nanosuit_2/tacmap_visibility_high"] = "255,255,128,0",
    ["nanosuit_2/tacmap_visibility_very_high"] = "255,255,0,0",
    ["nanosuit_2/tacmap_icon_default"] = "255,255,255,255",
    ["nanosuit_2/tacmap_icon_looted"] = "255,150,150,150",
    ["nanosuit_2/tacmap_icon_friend"] = "255,0,255,0",
    ["nanosuit_2/tacmap_icon_neutral"] = "255,255,255,0",
    ["nanosuit_2/tacmap_icon_enemy"] = "255,255,0,0",
    ["nanosuit_2/tacmap_icon_primary_task"] = "255,0,255,0",
    ["nanosuit_2/tacmap_icon_secondary_task"] = "255,255,255,0",
    -- nanosuit_2 theme, Auxiliaries UI
    ["nanosuit_2/auxiliaries_nv_energy"] = "255,253,254,50",
    ["nanosuit_2/auxiliaries_nv_energy_bg"] = "200,142,155,23",
    ["nanosuit_2/auxiliaries_nv_energy_off_bg"] = "200,24,24,24",
    -- nanosuit_2 theme, Indicators UI
    ["nanosuit_2/indicators_warning_low"] = "255,255,255,50",
    ["nanosuit_2/indicators_warning_medium"] = "255,255,125,50",
    ["nanosuit_2/indicators_warning_high"] = "255,255,50,50",
    -- Technical
    ["debug_mode"] = false
}

-- ---------------------------------------------------------------------------------------------------------------------
-- General functions
-- ---------------------------------------------------------------------------------------------------------------------

function get_outfit_config(key, default)
    local outfit = db.actor:item_in_slot(actor_slots_enum.outfit)
    if not outfit then
        return default
    end
    return get_config("configuration", outfit:section() .. "/" .. key, default)
end

function get_config(category, key, default)
    if ui_mcm then
        return ui_mcm.get("nanosuit/nanosuit_" .. category .. "/" .. key) or default
    end
    return defaults[key] or default
end

-- ---------------------------------------------------------------------------------------------------------------------
-- MCM UI definition
-- ---------------------------------------------------------------------------------------------------------------------

function on_mcm_load()
    op = {
        id = "nanosuit",
        gr = {
            {
                id = "nanosuit_general",
                sh = true,
                gr = {
                    { type = "slide", text = "ui_mcm_menu_nanosuit", link = "ui_nanosuit_mcm_banner", spacing = 20, size = { 512, 50 } },
                    { type = "title", text = "ui_mcm_menu_nanosuit_general" },
                    { type = "check", val = mcm_types_enum.boolean, id = "use_witness", def = defaults["use_witness"] },
                    { type = "check", val = mcm_types_enum.boolean, id = "customize_ammo_wheel", def = defaults["customize_ammo_wheel"] },
                    { type = "check", val = mcm_types_enum.boolean, id = "customize_companion_wheel", def = defaults["customize_companion_wheel"] },
                    { type = "check", val = mcm_types_enum.boolean, id = "customize_companion_list", def = defaults["customize_companion_list"] },
                    { type = "list", val = mcm_types_enum.string, id = "suit_gender", def = defaults["suit_gender"], no_str = true, content = { {gender_enum.male,"ui_mcm_nanosuit_nanosuit_general_suit_gender_lst_male"}, {gender_enum.female,"ui_mcm_nanosuit_nanosuit_general_suit_gender_lst_female"} } },
                }
            },
            {
                id = "nanosuit_keybindings",
                sh = true,
                gr = {
                    { type = "slide", text = "ui_mcm_menu_nanosuit", link = "ui_nanosuit_mcm_banner", spacing = 20, size = { 512, 50 } },
                    { type = "title", text = "ui_mcm_menu_nanosuit_keybindings" },
                    { type = "key_bind", val = mcm_types_enum.number, id = "suit_menu", def = defaults["suit_menu"] },
                    { type = "key_bind", val = mcm_types_enum.number, id = "nanovision", def = defaults["nanovision"], precondition = { function() return z_heatvision ~= nil end } },
                    { type = "key_bind", val = mcm_types_enum.number, id = "nightvision", def = defaults["nightvision"] },
                    { type = "key_bind", val = mcm_types_enum.number, id = "defibrillate", def = defaults["defibrillate"] },
                    { type = "key_bind", val = mcm_types_enum.number, id = "binoculars", def = defaults["binoculars"] },
                }
            },
            {
                id = "nanosuit_configuration",
                gr = {
                    {
                        id = "outfit_nanosuit",
                        text = "st_nanosuit_outfit_name_s",
                        sh = true,
                        gr = build_outfit_page("outfit_nanosuit", "st_nanosuit_outfit_name")
                    },
                    {
                        id = "outfit_nanosuit_2",
                        text = "st_nanosuit_2_outfit_name_s",
                        sh = true,
                        gr = build_outfit_page("outfit_nanosuit_2", "st_nanosuit_2_outfit_name")
                    },
                    {
                        id = "outfit_nanosuit_asian",
                        text = "st_nanosuit_asian_outfit_name_s",
                        sh = true,
                        gr = build_outfit_page("outfit_nanosuit_asian", "st_nanosuit_asian_outfit_name")
                    }
                }
            },
            {
                id = "nanosuit_hud_ui",
                gr = {
                    {
                        id = themes_enum.nanosuit_1,
                        text = "st_nanosuit_outfit_name_s",
                        sh = true,
                        gr = build_theme_page(themes_enum.nanosuit_1, "st_nanosuit_outfit_name")
                    },
                    {
                        id = themes_enum.nanosuit_2,
                        text = "st_nanosuit_2_outfit_name_s",
                        sh = true,
                        gr = build_theme_page(themes_enum.nanosuit_2, "st_nanosuit_2_outfit_name")
                    },
                    {
                        id = themes_enum.nanosuit_korean,
                        text = "st_nanosuit_asian_outfit_name_s",
                        sh = true,
                        gr = build_theme_page(themes_enum.nanosuit_korean, "st_nanosuit_asian_outfit_name")
                    }
                }
            },
            {
                id = "nanosuit_technical",
                sh = true,
                gr = {
                    { type = "slide", text = "ui_mcm_menu_nanosuit", link = "ui_nanosuit_mcm_banner", spacing = 20, size = { 512, 50 } },
                    { type = "title", text = "ui_mcm_menu_nanosuit_technical" },
                    { type = "check", val = mcm_types_enum.boolean, id = "debug_mode", def = defaults["debug_mode"] },
                }
            },
        }
    }

    return op
end

function build_outfit_page(section, name)
    return {
        { type = "slide", text = "ui_mcm_menu_nanosuit", link = "ui_nanosuit_mcm_banner", spacing = 20, size = { 512, 50 } },
        { type = "title", text = "ui_mcm_menu_nanosuit_configuration" },
        { type = "desc", text = name },
        { type = "line" },
        { type = "desc", text = "ui_mcm_nanosuit_nanosuit_configuration_general" },
        { type = "track", val = mcm_types_enum.number, id = "energy_use_factor", def = defaults[section .. "/energy_use_factor"], hint = "nanosuit_nanosuit_configuration_energy_use_factor", min = 0, max = defaults[section .. "/energy_use_factor"] * 2, step = 0.1 },
        { type = "track", val = mcm_types_enum.number, id = "energy_regen_factor", def = defaults[section .. "/energy_regen_factor"], hint = "nanosuit_nanosuit_configuration_energy_regen_factor", min = 0, max = defaults[section .. "/energy_regen_factor"] * 2, step = 0.1 },
        { type = "list", val = mcm_types_enum.string, id = "vision_perk", def = defaults[section .. "/vision_perk"], hint = "nanosuit_nanosuit_configuration_vision_perk", no_str = true, content = { {vision_perk_enum.nightvision,"ui_mcm_nanosuit_nanosuit_configuration_vision_perk_lst_nightvision"}, {vision_perk_enum.nanovision,"ui_mcm_nanosuit_nanosuit_configuration_vision_perk_lst_nanovision"} } },
        { type = "list", val = mcm_types_enum.string, id = "theme", def = defaults[section .. "/theme"], hint = "nanosuit_nanosuit_configuration_theme", no_str = true, content = { {themes_enum.nanosuit_1,"st_nanosuit_outfit_name_s"}, {themes_enum.nanosuit_korean,"st_nanosuit_asian_outfit_name_s"}, {themes_enum.nanosuit_2,"st_nanosuit_2_outfit_name_s"} } },
        { type = "line" },
        { type = "desc", text = "ui_mcm_nanosuit_nanosuit_configuration_armor" },
        { type = "track", val = mcm_types_enum.number, id = "protection_armor_burn", def = defaults[section .. "/protection_armor_burn"], hint = "nanosuit_nanosuit_configuration_burn", min = 0, max = defaults[section .. "/protection_armor_burn"] * 2, step = 0.1 },
        { type = "track", val = mcm_types_enum.number, id = "protection_armor_shock", def = defaults[section .. "/protection_armor_shock"], hint = "nanosuit_nanosuit_configuration_shock", min = 0, max = defaults[section .. "/protection_armor_shock"] * 2, step = 0.1 },
        { type = "track", val = mcm_types_enum.number, id = "protection_armor_chemical_burn", def = defaults[section .. "/protection_armor_chemical_burn"], hint = "nanosuit_nanosuit_configuration_chemical_burn", min = 0, max = defaults[section .. "/protection_armor_chemical_burn"] * 2, step = 0.1 },
        { type = "track", val = mcm_types_enum.number, id = "protection_armor_radiation", def = defaults[section .. "/protection_armor_radiation"], hint = "nanosuit_nanosuit_configuration_radiation", min = 0, max = defaults[section .. "/protection_armor_radiation"] * 2, step = 0.1 },
        { type = "track", val = mcm_types_enum.number, id = "protection_armor_wound", def = defaults[section .. "/protection_armor_wound"], hint = "nanosuit_nanosuit_configuration_wound", min = 0, max = defaults[section .. "/protection_armor_wound"] * 2, step = 0.1 },
        { type = "track", val = mcm_types_enum.number, id = "protection_armor_fire_wound", def = defaults[section .. "/protection_armor_fire_wound"], hint = "nanosuit_nanosuit_configuration_fire_wound", min = 0, max = defaults[section .. "/protection_armor_fire_wound"] * 2, step = 0.1 },
        { type = "track", val = mcm_types_enum.number, id = "protection_armor_strike", def = defaults[section .. "/protection_armor_strike"], hint = "nanosuit_nanosuit_configuration_strike", min = 0, max = defaults[section .. "/protection_armor_strike"] * 2, step = 0.1 },
        { type = "track", val = mcm_types_enum.number, id = "protection_armor_explosion", def = defaults[section .. "/protection_armor_explosion"], hint = "nanosuit_nanosuit_configuration_explosion", min = 0, max = defaults[section .. "/protection_armor_explosion"] * 2, step = 0.1 },
        { type = "track", val = mcm_types_enum.number, id = "protection_armor_wound_2", def = defaults[section .. "/protection_armor_wound_2"], hint = "nanosuit_nanosuit_configuration_wound_2", min = 0, max = defaults[section .. "/protection_armor_wound_2"] * 2, step = 0.1 },
        { type = "track", val = mcm_types_enum.number, id = "protection_armor_light_burn", def = defaults[section .. "/protection_armor_light_burn"], hint = "nanosuit_nanosuit_configuration_light_burn", min = 0, max = defaults[section .. "/protection_armor_light_burn"] * 2, step = 0.1 },
        { type = "line" },
        { type = "desc", text = "ui_mcm_nanosuit_nanosuit_configuration_cloak" },
        { type = "track", val = mcm_types_enum.number, id = "protection_cloak_radiation", def = defaults[section .. "/protection_cloak_radiation"], hint = "nanosuit_nanosuit_configuration_radiation", min = 0, max = defaults[section .. "/protection_cloak_radiation"] * 2, step = 0.1 },
        { type = "line" },
        { type = "desc", text = "ui_mcm_nanosuit_nanosuit_configuration_power" },
        { type = "track", val = mcm_types_enum.number, id = "protection_power_radiation", def = defaults[section .. "/protection_power_radiation"], hint = "nanosuit_nanosuit_configuration_radiation", min = 0, max = defaults[section .. "/protection_power_radiation"] * 2, step = 0.1 },
        { type = "track", val = mcm_types_enum.number, id = "protection_power_strike", def = defaults[section .. "/protection_power_strike"], hint = "nanosuit_nanosuit_configuration_strike", min = 0, max = defaults[section .. "/protection_power_strike"] * 2, step = 0.1 },
        { type = "line" },
        { type = "desc", text = "ui_mcm_nanosuit_nanosuit_configuration_speed" },
        { type = "track", val = mcm_types_enum.number, id = "protection_speed_radiation", def = defaults[section .. "/protection_speed_radiation"], hint = "nanosuit_nanosuit_configuration_radiation", min = 0, max = defaults[section .. "/protection_speed_radiation"] * 2, step = 0.1 },
    }
end

function build_theme_page(theme, name)
    return {
        { type = "slide", text = "ui_mcm_menu_nanosuit", link = "ui_nanosuit_mcm_banner", spacing = 20, size = { 512, 50 } },
        { type = "title", text = "ui_mcm_menu_nanosuit_hud_ui" },
        { type = "desc", text = name },
        { type = "line" },
        { type = "desc", text = "ui_mcm_nanosuit_nanosuit_hud_ui_general" },
        { type = "input", val = mcm_types_enum.string, id = "text", def = defaults[theme .. "/text"], hint = "nanosuit_nanosuit_hud_ui_text", ui_hook_functor = { ui_mcm_argb_input.init_mcm_argb_control } },
        { type = "input", val = mcm_types_enum.string, id = "outline", def = defaults[theme .. "/outline"], hint = "nanosuit_nanosuit_hud_ui_outline", ui_hook_functor = { ui_mcm_argb_input.init_mcm_argb_control } },
        { type = "input", val = mcm_types_enum.string, id = "accent", def = defaults[theme .. "/accent"], hint = "nanosuit_nanosuit_hud_ui_accent", ui_hook_functor = { ui_mcm_argb_input.init_mcm_argb_control } },
        { type = "input", val = mcm_types_enum.string, id = "alert", def = defaults[theme .. "/alert"], hint = "nanosuit_nanosuit_hud_ui_alert", ui_hook_functor = { ui_mcm_argb_input.init_mcm_argb_control } },
        { type = "input", val = mcm_types_enum.string, id = "background", def = defaults[theme .. "/background"], hint = "nanosuit_nanosuit_hud_ui_background", ui_hook_functor = { ui_mcm_argb_input.init_mcm_argb_control } },
        { type = "line" },
        { type = "desc", text = "ui_mcm_nanosuit_nanosuit_hud_ui_status" },
        { type = "input", val = mcm_types_enum.string, id = "status_energy", def = defaults[theme .. "/status_energy"], hint = "nanosuit_nanosuit_hud_ui_status_energy", ui_hook_functor = { ui_mcm_argb_input.init_mcm_argb_control } },
        { type = "input", val = mcm_types_enum.string, id = "status_energy_bg", def = defaults[theme .. "/status_energy_bg"], hint = "nanosuit_nanosuit_hud_ui_status_energy_bg", ui_hook_functor = { ui_mcm_argb_input.init_mcm_argb_control } },
        { type = "input", val = mcm_types_enum.string, id = "status_energy_off_bg", def = defaults[theme .. "/status_energy_off_bg"], hint = "nanosuit_nanosuit_hud_ui_status_energy_off_bg", ui_hook_functor = { ui_mcm_argb_input.init_mcm_argb_control } },
        { type = "input", val = mcm_types_enum.string, id = "status_health", def = defaults[theme .. "/status_health"], hint = "nanosuit_nanosuit_hud_ui_status_health", ui_hook_functor = { ui_mcm_argb_input.init_mcm_argb_control } },
        { type = "input", val = mcm_types_enum.string, id = "status_health_bg", def = defaults[theme .. "/status_health_bg"], hint = "nanosuit_nanosuit_hud_ui_status_health_bg", ui_hook_functor = { ui_mcm_argb_input.init_mcm_argb_control } },
        { type = "input", val = mcm_types_enum.string, id = "status_health_off_bg", def = defaults[theme .. "/status_health_off_bg"], hint = "nanosuit_nanosuit_hud_ui_status_health_off_bg", ui_hook_functor = { ui_mcm_argb_input.init_mcm_argb_control } },
        { type = "input", val = mcm_types_enum.string, id = "status_stamina", def = defaults[theme .. "/status_stamina"], hint = "nanosuit_nanosuit_hud_ui_status_stamina", ui_hook_functor = { ui_mcm_argb_input.init_mcm_argb_control } },
        { type = "input", val = mcm_types_enum.string, id = "status_stamina_bg", def = defaults[theme .. "/status_stamina_bg"], hint = "nanosuit_nanosuit_hud_ui_status_stamina_bg", ui_hook_functor = { ui_mcm_argb_input.init_mcm_argb_control } },
        { type = "input", val = mcm_types_enum.string, id = "status_stamina_off_bg", def = defaults[theme .. "/status_stamina_off_bg"], hint = "nanosuit_nanosuit_hud_ui_status_stamina_off_bg", ui_hook_functor = { ui_mcm_argb_input.init_mcm_argb_control } },
        { type = "line" },
        { type = "desc", text = "ui_mcm_nanosuit_nanosuit_hud_ui_tacmap" },
        { type = "input", val = mcm_types_enum.string, id = "tacmap_map", def = defaults[theme .. "/tacmap_map"], hint = "nanosuit_nanosuit_hud_ui_tacmap_map", ui_hook_functor = { ui_mcm_argb_input.init_mcm_argb_control } },
        { type = "input", val = mcm_types_enum.string, id = "tacmap_visibility_bg", def = defaults[theme .. "/tacmap_visibility_bg"], hint = "nanosuit_nanosuit_hud_ui_tacmap_visibility_bg", ui_hook_functor = { ui_mcm_argb_input.init_mcm_argb_control } },
        { type = "input", val = mcm_types_enum.string, id = "tacmap_visibility_very_low", def = defaults[theme .. "/tacmap_visibility_very_low"], hint = "nanosuit_nanosuit_hud_ui_tacmap_visibility_very_low", ui_hook_functor = { ui_mcm_argb_input.init_mcm_argb_control } },
        { type = "input", val = mcm_types_enum.string, id = "tacmap_visibility_low", def = defaults[theme .. "/tacmap_visibility_low"], hint = "nanosuit_nanosuit_hud_ui_tacmap_visibility_low", ui_hook_functor = { ui_mcm_argb_input.init_mcm_argb_control } },
        { type = "input", val = mcm_types_enum.string, id = "tacmap_visibility_high", def = defaults[theme .. "/tacmap_visibility_high"], hint = "nanosuit_nanosuit_hud_ui_tacmap_visibility_high", ui_hook_functor = { ui_mcm_argb_input.init_mcm_argb_control } },
        { type = "input", val = mcm_types_enum.string, id = "tacmap_visibility_very_high", def = defaults[theme .. "/tacmap_visibility_very_high"], hint = "nanosuit_nanosuit_hud_ui_tacmap_visibility_very_high", ui_hook_functor = { ui_mcm_argb_input.init_mcm_argb_control } },
        { type = "input", val = mcm_types_enum.string, id = "tacmap_icon_default", def = defaults[theme .. "/tacmap_icon_default"], hint = "nanosuit_nanosuit_hud_ui_tacmap_icon_default", ui_hook_functor = { ui_mcm_argb_input.init_mcm_argb_control } },
        { type = "input", val = mcm_types_enum.string, id = "tacmap_icon_looted", def = defaults[theme .. "/tacmap_icon_looted"], hint = "nanosuit_nanosuit_hud_ui_tacmap_icon_looted", ui_hook_functor = { ui_mcm_argb_input.init_mcm_argb_control } },
        { type = "input", val = mcm_types_enum.string, id = "tacmap_icon_friend", def = defaults[theme .. "/tacmap_icon_friend"], hint = "nanosuit_nanosuit_hud_ui_tacmap_icon_friend", ui_hook_functor = { ui_mcm_argb_input.init_mcm_argb_control } },
        { type = "input", val = mcm_types_enum.string, id = "tacmap_icon_neutral", def = defaults[theme .. "/tacmap_icon_neutral"], hint = "nanosuit_nanosuit_hud_ui_tacmap_icon_neutral", ui_hook_functor = { ui_mcm_argb_input.init_mcm_argb_control } },
        { type = "input", val = mcm_types_enum.string, id = "tacmap_icon_enemy", def = defaults[theme .. "/tacmap_icon_enemy"], hint = "nanosuit_nanosuit_hud_ui_tacmap_icon_enemy", ui_hook_functor = { ui_mcm_argb_input.init_mcm_argb_control } },
        { type = "input", val = mcm_types_enum.string, id = "tacmap_icon_primary_task", def = defaults[theme .. "/tacmap_icon_primary_task"], hint = "nanosuit_nanosuit_hud_ui_tacmap_icon_primary_task", ui_hook_functor = { ui_mcm_argb_input.init_mcm_argb_control } },
        { type = "input", val = mcm_types_enum.string, id = "tacmap_icon_secondary_task", def = defaults[theme .. "/tacmap_icon_secondary_task"], hint = "nanosuit_nanosuit_hud_ui_tacmap_icon_secondary_task", ui_hook_functor = { ui_mcm_argb_input.init_mcm_argb_control } },
        { type = "line" },
        { type = "desc", text = "ui_mcm_nanosuit_nanosuit_hud_ui_auxiliaries" },
        { type = "input", val = mcm_types_enum.string, id = "auxiliaries_nv_energy", def = defaults[theme .. "/auxiliaries_nv_energy"], hint = "nanosuit_nanosuit_hud_ui_auxiliaries_nv_energy", ui_hook_functor = { ui_mcm_argb_input.init_mcm_argb_control } },
        { type = "input", val = mcm_types_enum.string, id = "auxiliaries_nv_energy_bg", def = defaults[theme .. "/auxiliaries_nv_energy_bg"], hint = "nanosuit_nanosuit_hud_ui_auxiliaries_nv_energy_bg", ui_hook_functor = { ui_mcm_argb_input.init_mcm_argb_control } },
        { type = "input", val = mcm_types_enum.string, id = "auxiliaries_nv_energy_off_bg", def = defaults[theme .. "/auxiliaries_nv_energy_off_bg"], hint = "nanosuit_nanosuit_hud_ui_auxiliaries_nv_energy_off_bg", ui_hook_functor = { ui_mcm_argb_input.init_mcm_argb_control } },
        { type = "line" },
        { type = "desc", text = "ui_mcm_nanosuit_nanosuit_hud_ui_indicators" },
        { type = "input", val = mcm_types_enum.string, id = "indicators_warning_low", def = defaults[theme .. "/indicators_warning_low"], hint = "nanosuit_nanosuit_hud_ui_indicators_warning_low", ui_hook_functor = { ui_mcm_argb_input.init_mcm_argb_control } },
        { type = "input", val = mcm_types_enum.string, id = "indicators_warning_medium", def = defaults[theme .. "/indicators_warning_medium"], hint = "nanosuit_nanosuit_hud_ui_indicators_warning_medium", ui_hook_functor = { ui_mcm_argb_input.init_mcm_argb_control } },
        { type = "input", val = mcm_types_enum.string, id = "indicators_warning_high", def = defaults[theme .. "/indicators_warning_high"], hint = "nanosuit_nanosuit_hud_ui_indicators_warning_high", ui_hook_functor = { ui_mcm_argb_input.init_mcm_argb_control } },
    }
end