---==================================================================================================================---
---                                                                                                                  ---
---    Original Author(s) : NLTP_ASHES                                                                               ---
---    Edited : N/A                                                                                                  ---
---    Date : 26/07/2025                                                                                             ---
---    License : Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)           ---
---                                                                                                                  ---
---    Script used to handle the animated sequence of the vaporization.                                              ---
---                                                                                                                  ---
---==================================================================================================================---

-- ---------------------------------------------------------------------------------------------------------------------
-- Constants, global variables and imported functions
-- ---------------------------------------------------------------------------------------------------------------------

-- Imports
hit_types_enum          = nanosuit_utils.hit_types_enum
actor_cameras_enum      = nanosuit_utils.actor_cameras_enum

-- ---------------------------------------------------------------------------------------------------------------------
-- Vaporization sequence class
-- ---------------------------------------------------------------------------------------------------------------------

class "vaporization_sequence" (nanosuit_sequence.scripted_sequence)

function vaporization_sequence:__init(id) super()
    self.m_id = id
    self.m_vaporizing = true
    self.m_burning = false
    self.m_particles = {}
    self.m_vaporize_sfx = {
        hud = sound_object([[nanosuit\misc\vaporize_hud]]),
        world = sound_object([[nanosuit\misc\vaporize_world]])
    }
end

function vaporization_sequence:destroy()
    nanosuit_sequence.scripted_sequence.destroy(self)

    self.m_particles = {}
end

function vaporization_sequence:execute()
    nanosuit_sequence.scripted_sequence.execute(self)

    -- Reset particles
    self.m_particles = {}
end

function vaporization_sequence:update()
    nanosuit_sequence.scripted_sequence.update(self)

    if not self.m_vaporizing then
        return
    end

    local obj = level.object_by_id(self.m_id)
    if not obj then
        return
    end

    -- Update sound effects
    if obj:id() ~= AC_ID and self.m_vaporize_sfx.world:playing() then
        self.m_vaporize_sfx.world:set_position(obj:position())
    end

    -- Update particles
    if self.m_burning then
        local hud_mode = obj:id() == AC_ID and level.get_active_cam() == actor_cameras_enum.first_eye
        local bones = obj:list_bones(hud_mode)
        for bone_id, bone_name in pairs(bones) do
            if not self.m_particles[bone_name] then
                self.m_particles[bone_name] = particles_object([[nanosuit\vaporize\vaporize]])
            end

            if not self.m_particles[bone_name]:playing() then
                self.m_particles[bone_name]:play(hud_mode)
            end

            self.m_particles[bone_name]:set_hud_mode(hud_mode)
            self.m_particles[bone_name]:move_to(obj:bone_position(bone_id, hud_mode), VEC_ZERO)
        end
    end
end

function vaporization_sequence:wait_for_state()
    -- Actor
    if self.m_id == AC_ID then
        return true
    end

    local obj = level.object_by_id(self.m_id)
    if not obj then
        return true
    end

    -- NPC
    local state = state_mgr.get_state(obj)
    if state and state == nanosuit_vaporizer.vaporize_state then
        return true
    end

    return false
end

function vaporization_sequence:action_notify_witness()
    local header = nanosuit_utils.get_translation("Nanosuit") -- TODO : Translate that
    local message = nanosuit_utils.get_translation("You have let someone who saw you escape, you will be terminated.") -- TODO : Translate that
    local duration = 5
    local icon = "ui_inGame2_no_data"
    dynamic_news_helper.send_tip(message, header, nil, duration, icon, "beep_1", "npc")

    return true
end

function vaporization_sequence:action_sounds()
    local obj = level.object_by_id(self.m_id)
    if not obj then
        return true
    end
    
    local snd = obj:id() == AC_ID and self.m_vaporize_sfx.hud or self.m_vaporize_sfx.world
    if obj:id() == AC_ID and snd:playing() then
        snd:play_at_pos(obj, VEC_ZERO, 0, sound_object.s2d)
    else
        snd:play_at_pos(obj, obj:position())
    end

    return true
end

function vaporization_sequence:action_burn()
    self.m_burning = true
    return true
end

function vaporization_sequence:action_kill()
    local obj = level.object_by_id(self.m_id)
    if not obj then
        return true
    end

    -- Kill object if alive
    if obj:alive() then
        local h = hit()
        h.power = 1000
        h.direction = obj:direction()
        h.bone = "bip01_spine"
        h.draftsman = obj
        h.impulse = 20
        h.type = hit_types_enum.burn
        obj:hit(h)
    end

    return true
end

function vaporization_sequence:action_force_kill()
    local obj = level.object_by_id(self.m_id)
    if not obj then
        return true
    end

    -- Force kill object if still alive
    if obj:alive() then
        obj:kill(obj)
    end

    return true
end

function vaporization_sequence:action_hide_body()
    local obj = level.object_by_id(self.m_id)
    if not obj then
        return true
    end

    -- Hide body
    for _, hud_mode in pairs({ true, false }) do
        for idx in pairs(obj:get_shaders()) do
            obj:set_shader(idx, [[models\lightplanes]], [[nanosuit\no_draw]], hud_mode)
        end
    end

    return true
end

function vaporization_sequence:action_stop_burn()
    -- Stop particles
    for bone_name, particle in pairs(self.m_particles) do
        if particle:playing() then
            particle:stop_deffered()
        end
    end

    self.m_burning = false
    return true
end

-- FIXME : If actor interacts with NPC, this will crash their game
function vaporization_sequence:action_release_npc()
    if self.m_id ~= AC_ID then
        local se_obj = alife_object(self.m_id)
        if se_obj then
            safe_release_manager.release(se_obj)
        end
    end

    self.m_vaporizing = false
    return true
end