---==================================================================================================================---
---                                                                                                                  ---
---    Original Author(s) : NLTP_ASHES                                                                               ---
---    Edited : N/A                                                                                                  ---
---    Date : 05/05/2026                                                                                             ---
---    License : Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)           ---
---                                                                                                                  ---
---    Script used to handle the Nanosuit tactical map task arrows UI.                                               ---
---                                                                                                                  ---
---==================================================================================================================---

-- ---------------------------------------------------------------------------------------------------------------------
-- Constants, global variables and imported functions
-- ---------------------------------------------------------------------------------------------------------------------

-- ---------------------------------------------------------------------------------------------------------------------
-- Tactical map icon UI class
-- ---------------------------------------------------------------------------------------------------------------------

class "ui_tacmap_task_arrow"

function ui_tacmap_task_arrow:__init(container)
    -- Variables
    self.m_primary_task_color = GetARGB(255, 0, 255, 0)
    self.m_secondary_task_color = GetARGB(255, 255, 255, 0)

    -- Build UI
    self.m_xml = CScriptXmlInit()
    self.m_xml:ParseFile("ui_nanosuit_tacmap.xml")

    -- Main object icon
    self.arrow_static = self.m_xml:InitStatic("icon", container)
    self.arrow_static:InitTexture("ui_nanosuit_tacmap_task_arrow")
    self.arrow_static:SetAutoDelete(true)
end

function ui_tacmap_task_arrow:__finalize()
end

function ui_tacmap_task_arrow:destroy(container)
    container:DetachChild(self.arrow_static)
end

function ui_tacmap_task_arrow:update(obj, hud_pos, hud_dir)
    if hud_pos and hud_dir then
        arm.move_and_center_element(self.arrow_static, hud_pos.x, hud_pos.y)
        self.arrow_static:SetHeading(hud_dir)
    end

    self.arrow_static:SetTextureColor(nanosuit_utils.is_task_target(obj:id(), "primary") and self.m_primary_task_color or self.m_secondary_task_color)

    -- Mark as refreshed
    self.refreshed = true
end
