---==================================================================================================================---
---                                                                                                                  ---
---    Original Author(s) : NLTP_ASHES                                                                               ---
---    Edited : N/A                                                                                                  ---
---    Date : 19/09/2026                                                                                             ---
---    License : Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)           ---
---                                                                                                                  ---
---    Script used to handle the logic of a melee damage booster usable by a Nanosuit mode.                          ---
---                                                                                                                  ---
---==================================================================================================================---

-- ---------------------------------------------------------------------------------------------------------------------
-- Constants, global variables and imported functions
-- ---------------------------------------------------------------------------------------------------------------------

-- Imports
actor_slots_enum        = nanosuit_utils.actor_slots_enum

-- ---------------------------------------------------------------------------------------------------------------------
-- Item booster class
-- ---------------------------------------------------------------------------------------------------------------------

class "melee" (nanosuit_booster_item.abstract_item_booster)

function melee:__init(core, name) super(core, name)
    self.m_power_factor = 2
    self.m_impulse_factor = 10

    -- Cache
    self.m_cache[actor_slots_enum.knife] = { enabled = true, obj_id = nil }
end

function melee:filter(obj, slot)
    if not nanosuit_booster_item.abstract_item_booster.filter(self, obj, slot) then
        return false
    end
    return IsMelee(obj) and obj:cast_Knife()
end

function melee:set(obj, slot)
    nanosuit_booster_item.abstract_item_booster.set(self, obj, slot)

    local wpn_obj = obj:cast_Knife()
    wpn_obj:SetHit1Power(wpn_obj:GetHit1Power() * self.m_power_factor)
    wpn_obj:SetHit2Power(wpn_obj:GetHit2Power() * self.m_power_factor)
    wpn_obj:SetHit1PowerCritical(wpn_obj:GetHit1PowerCritical() * self.m_power_factor)
    wpn_obj:SetHit2PowerCritical(wpn_obj:GetHit2PowerCritical() * self.m_power_factor)
    wpn_obj:SetHit1Impulse(wpn_obj:GetHit1Impulse() * self.m_impulse_factor)
    wpn_obj:SetHit2Impulse(wpn_obj:GetHit2Impulse() * self.m_impulse_factor)
end

function melee:unset(obj, slot)
    local wpn_obj = obj:cast_Knife()
    wpn_obj:SetHit1Power(wpn_obj:GetHit1Power() / self.m_power_factor)
    wpn_obj:SetHit2Power(wpn_obj:GetHit2Power() / self.m_power_factor)
    wpn_obj:SetHit1PowerCritical(wpn_obj:GetHit1PowerCritical() / self.m_power_factor)
    wpn_obj:SetHit2PowerCritical(wpn_obj:GetHit2PowerCritical() / self.m_power_factor)
    wpn_obj:SetHit1Impulse(wpn_obj:GetHit1Impulse() / self.m_impulse_factor)
    wpn_obj:SetHit2Impulse(wpn_obj:GetHit2Impulse() / self.m_impulse_factor)

    nanosuit_booster_item.abstract_item_booster.unset(self, obj, slot)
end
