---==================================================================================================================---
---                                                                                                                  ---
---    Original Author(s) : NLTP_ASHES                                                                               ---
---    Edited : N/A                                                                                                  ---
---    Date : 03/05/2026                                                                                             ---
---    License : Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)           ---
---                                                                                                                  ---
---    Script used to handle the Nanosuit tactical map icon UI.                                                      ---
---                                                                                                                  ---
---==================================================================================================================---

-- ---------------------------------------------------------------------------------------------------------------------
-- Constants, global variables and imported functions
-- ---------------------------------------------------------------------------------------------------------------------

-- ---------------------------------------------------------------------------------------------------------------------
-- Tactical map icon UI class
-- ---------------------------------------------------------------------------------------------------------------------

class "ui_tacmap_icon"

function ui_tacmap_icon:__init(container)
    -- Variables
    self.m_default_color = GetARGB(255, 255, 255, 255)
    self.m_corpse_looted_color = GetARGB(255, 150, 150, 150)
    self.m_primary_task_color = GetARGB(255, 0, 255, 0)
    self.m_secondary_task_color = GetARGB(255, 255, 255, 0)
    self.m_color_per_relation = {
        [game_object.friend] = GetARGB(255, 0, 255, 0),
        [game_object.neutral] = GetARGB(255, 255, 255, 0),
        [game_object.enemy] = GetARGB(255, 255, 0, 0)
    }

    -- Build UI
    self.m_xml = CScriptXmlInit()
    self.m_xml:ParseFile("ui_nanosuit_tacmap.xml")

    -- Main object icon
    self.m_icon_static = self.m_xml:InitStatic("icon", container)
    self.m_icon_static:SetAutoDelete(true)

    -- Primary task icon
    self.m_primary_task_static = self.m_xml:InitStatic("icon", container)
    self.m_primary_task_static:InitTexture("ui_nanosuit_tacmap_task_point")
    self.m_primary_task_static:SetTextureColor(self.m_primary_task_color)
    self.m_primary_task_static:Show(false)
    self.m_primary_task_static:SetAutoDelete(true)

    -- Secondary task icon
    self.m_secondary_task_static = self.m_xml:InitStatic("icon", container)
    self.m_secondary_task_static:InitTexture("ui_nanosuit_tacmap_task_point")
    self.m_secondary_task_static:SetTextureColor(self.m_secondary_task_color)
    self.m_secondary_task_static:Show(false)
    self.m_secondary_task_static:SetAutoDelete(true)
end

function ui_tacmap_icon:__finalize()
end

function ui_tacmap_icon:destroy(container)
    -- Detach child statics
    container:DetachChild(self.m_icon_static)
    container:DetachChild(self.m_primary_task_static)
    container:DetachChild(self.m_secondary_task_static)
end

function ui_tacmap_icon:update(obj, hud_pos, hud_dir)
    -- Update statics
    self.m_icon_static:SetHeading(self:get_heading(obj, hud_dir))
    self.m_icon_static:InitTexture(self:get_texture(obj))
    self.m_icon_static:SetTextureColor(self:get_color(obj))
    self.m_icon_static:SetWndSize(self:get_size(obj))
    self.m_primary_task_static:Show(nanosuit_utils.is_task_target(obj:id(), "primary"))
    self.m_secondary_task_static:Show(nanosuit_utils.is_task_target(obj:id(), "secondary"))

    -- Center statics on coordinates
    arm.move_and_center_element(self.m_icon_static, hud_pos.x, hud_pos.y)
    arm.move_and_center_element(self.m_primary_task_static, hud_pos.x, hud_pos.y)
    arm.move_and_center_element(self.m_secondary_task_static, hud_pos.x, hud_pos.y)

    -- Mark as refreshed
    self.refreshed = true
end

function ui_tacmap_icon:get_texture(obj)
    if IsInvbox(obj) then
        return "ui_nanosuit_no_draw"
    end
    if IsCar(obj) then
        return "ui_nanosuit_tacmap_vehicle"
    end
    if (IsStalker(obj) or IsMonster(obj)) and not obj:alive() then
        return "ui_nanosuit_tacmap_body"
    end
    return "ui_nanosuit_tacmap_object"
end

function ui_tacmap_icon:get_color(obj)
    if IsStalker(obj) and obj:alive() then
        local relation = obj:relation(db.actor)
        return self.m_color_per_relation[relation]
    end
    if (IsStalker(obj) or IsMonster(obj)) and not obj:alive() then
        local is_stalker_looted = se_load_var(obj:id(), obj:name(), "death_dropped")
        local is_mutant_looted = se_load_var(obj:id(), obj:name(), "looted")
        if is_stalker_looted or is_mutant_looted then
            return self.m_corpse_looted_color
        end
    end
    return self.m_default_color
end

function ui_tacmap_icon:get_size(obj)
    if IsCar(obj) then
        return vector2():set(15, 15)
    end
    return vector2():set(10, 10)
end

function ui_tacmap_icon:get_heading(obj, dir)
    if IsCar(obj) then
        return dir
    end
    if (IsStalker(obj) or IsMonster(obj)) and obj:alive() then
        return dir
    end
    return 0
end
