---==================================================================================================================---
---                                                                                                                  ---
---    Original Author(s) : NLTP_ASHES                                                                               ---
---    Edited : N/A                                                                                                  ---
---    Date : 29/08/2026                                                                                             ---
---    License : Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)           ---
---                                                                                                                  ---
---    Script used to stylize the companion wheel UI like the rest of the Nanosuit HUD.                              ---
---                                                                                                                  ---
---==================================================================================================================---

-- ---------------------------------------------------------------------------------------------------------------------
-- Constants, global variables and imported functions
-- ---------------------------------------------------------------------------------------------------------------------

-- ---------------------------------------------------------------------------------------------------------------------
-- Companion wheel UI class
-- ---------------------------------------------------------------------------------------------------------------------

class "ui_wheel_companion" (CUIScriptWnd)

function ui_wheel_companion:__init(parent) super()
    -- Variables
    self.m_parent = parent

    -- Initialize companion wheel if needed
    if not axr_companions.GUI then
        printf("[ASH] creating companion UI")
        axr_companions.GUI = axr_companions.UIWheelCompanion()
    else
        printf("[ASH] companion UI already exists")
    end

    -- Create outline
    axr_companions.GUI.outline = axr_companions.GUI.xml:InitStatic("wheel:background", axr_companions.GUI.dialog)
    axr_companions.GUI.outline:InitTexture("ui_nanosuit_ammo_wheel_outline")

    -- Override background
    axr_companions.GUI.background = axr_companions.GUI.dialog:FindChild("wheel_background"):cast_Static()
    axr_companions.GUI.background:InitTexture("ui_nanosuit_ammo_wheel_background")
    axr_companions.GUI.background:SetTextureColor(GetARGB(200, 255, 255, 255))
end

function ui_wheel_companion:destroy()
    -- Destroy outline
    axr_companions.GUI.dialog:DetachChild(axr_companions.GUI.outline)
    axr_companions.GUI.outline = nil

    -- Reset UI
    axr_companions.GUI:InitControls()
end

function ui_wheel_companion:Update(force)
    CUIScriptWnd.Update(self)

    if self.m_parent.m_core.m_malfunctor.m_enabled then
        axr_companions.GUI.outline:SetTextureColor(self.m_parent.m_colors.red)
    else
        axr_companions.GUI.outline:SetTextureColor(self.m_parent.m_colors.background)
    end
end
